config/nrfconnect/chip-module/zephyr/module.yml
zephyr/module.yml

Add Zephyr module manifest in the CHIP root directory in order to automatically pull CHIP into a project when CHIP is one of the submodules specified in west manifest.

[nrf noup] Add Zephyr module manifest in the CHIP root directory

---

src/controller/CHIPDeviceController.cpp
src/crypto/CHIPCryptoPAL.h
src/crypto/CHIPCryptoPALOpenSSL.cpp
src/crypto/CHIPCryptoPALmbedTLS.cpp
src/lib/support/SafePointerCast.h

* Fix a bug in CHIP which may lead to executing mbedTLS code on unaligned data structures.
* Fix a bug in Android CHIPTool which causes a crash when trying to commission a device for the second time.

Fix ARM unaligned access and Android CHIPTool crash

---

.gitmodules

Previous pigweed location is blocked in some countries. Use the pigweed github fork, instead.

[nrf fromtree] Switch pigweed repo to point to github (#5316)

---

zephyr/module.yml

Matter module takes all compilatinon flags associated with
the zephyr_interface target and passes them to the external
GN-based project. For that reason we must ensure that the
Matter module is processed after other revelant modules
that modify the zephyr_interface target. nrfxlib is such
a module as it contains nrf_security which carries the
mbedtls configuration.

[nrf noup] Add a dependency on nrfxlib

---

config/nrfconnect/chip-module/CMakeLists.txt

-IF CONFIG_NRF_SECURITY_BACKEND - Add includes from mbedtls_external
Signed-off-by: Frank Audun Kvamtrø <frank.kvamtro@nordicsemi.no>

[nrf_noup]: Fix nrf_security includes for matter

---

config/nrfconnect/chip-module/CMakeLists.txt
config/nrfconnect/chip-module/make_gn_args.py

This commit fixes issue with maximum command length on Windows.
Signed-off-by: Lukasz Duda <lukasz.duda@nordicsemi.no>

[nrf toup] reduce command parameters length

---

.github/workflows/release_tools.yaml

Add a manually triggered workflow for building Android
CHIPTool packages for arm and arm64 architectures, and
Python CHIP Controller for Linux x64 and arm64.
The packages are uploaded both as github artifacts and
release packages (as the latter require a release tag).

[nrf noup] add workflow for building CHIP tools

---

examples/lighting-app/nrfconnect/main/AppTask.cpp
examples/lock-app/nrfconnect/main/AppTask.cpp
examples/platform/nrfconnect/util/DFUOverSMP.cpp
examples/platform/nrfconnect/util/include/DFUOverSMP.h
src/android/CHIPTool/app/src/main/AndroidManifest.xml
src/include/platform/CHIPDeviceEvent.h
src/platform/Zephyr/BLEManagerImpl.cpp

Cherry-picked two commits from upstream that contain fixes for the following bugs:
* Incorrect BLE disconnect handling and fixes for advertising switching between CHIPoBLE and SMP.
* Incorrect NFC URI scheme in Android CHIPTool app (change from CHIP to Matter CH->MT).

Cherry-picked two bug fixing commits

---

.github/workflows/release_tools.yaml

Added configuration that builds Python CHIP controller with
detail logs disabled in order to reduce number of output logs
and make writing commands easier.

[nrf noup] Added to release workflow chip controller release build

---

src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/CHIPToolActivity.kt

This PR ensures that the BLE connection is closed after PASE session.
Signed-off-by: Lukasz Duda <lukasz.duda@nordicsemi.no>

[nrf fromlist] Close BLE connection after commissioning.

---

src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp

In the recent OpenThread versions, a new parameter has been
added to the otSrpClientRemoveHostAndServices() function.

[nrf noup] Fix build with new OpenThread

---

src/lib/support/SafePointerCast.h

This file has a 2020 copyright upstream, but commit
00ac05f5fd880aad6acf332b198353696b9ddf9e
("[nrf fromup] Fix unaligned access or ARM") pulls it in with a
different date.
Reconcile the difference before taking a snapshot of the repository
for history rewrite.
This allows us to rebase cleanly.
Change to a comment.
No testing is required because comments are semantically irrelevant.

[nrf noup] SafePointerCast.h: match upstream version

---

src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/SensorClientFragment.kt

In some Android SDK versions spawning a DNS-SD query when a previous one is still in progress results in an error.
Change the device address update condition so that two identical queries are not sent on entering the sensor
clusters screen, not to generate a failure.

[nrf noup] Fix issue with spawning multiple DNS-SD queries

---

.github/workflows/release_tools.yaml

Disable apt-get immediate configuration that was causing trouble.

[nrf noup] Fix "Release Tools" workflow

---

examples/chip-tool/commands/discover/Commands.h
src/app/OperationalDeviceProxy.cpp
src/controller/CHIPDeviceController.cpp
src/controller/python/chip/discovery/NodeResolution.cpp
src/controller/tests/TestCommissionableNodeController.cpp
src/lib/dnssd/Discovery_ImplPlatform.cpp
src/lib/dnssd/Discovery_ImplPlatform.h
src/lib/dnssd/Resolver.h
src/lib/dnssd/Resolver_ImplMinimalMdns.cpp
src/lib/dnssd/Resolver_ImplNone.cpp
src/lib/shell/commands/Dns.cpp

DNS-SD records are cached, so in case of device IP address change
and trying to resolve address again the cached value is used
instead of the new one.
Added argument that allows to bypass reading DNS-SD services data
from cache.

[nrf fromlist] Added argument allowing to bypass caching DNS-SD.

---

.github/workflows/release_tools.yaml
examples/chip-tool/commands/pairing/PairingCommand.cpp
src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/SensorClientFragment.kt
src/controller/CHIPDeviceController.cpp
src/controller/CHIPDeviceController.h
src/controller/java/CHIPDeviceController-JNI.cpp

* The app crashes on entering the sensor cluster screen.
* The app incorrectly invokes the admin ECM command.
* The release_tools.yml workflow generates too big packages.

Fix issues with Android CHIPTool

---

src/platform/Zephyr/NFCManagerImpl.cpp

The new version of the NFC library has a slightly
changed api. This commit alignes to use the new API.
* Fixes building of the Matter samples
Alignment to the new NFC API
Testing isn't required because the functionality of the NFC library hasn't be changed

Alignment to the new NFC library version

---

src/messaging/ExchangeContext.cpp
src/platform/Zephyr/BLEManagerImpl.cpp

The commissioner starts operational node discovery and CASE
with the commissionee without dropping the BLE connection
and it's the reposibility of the commissionee to drop the
BLE connection upon reception of Sigma 1.
Exchanging quite big Sigma messages while still maintaining
the BLE connection may cause frame drops on a Thread Sleepy
End Device depending on the device BLE configuration.
Drop the BLE connection on the commissioner side as soon as
it's no longer needed.
What is being fixed?  Examples:
* Fix crash on startup
* Fixes #12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).
What's in this PR
How was this tested? (at least one bullet point required)
* If unit tests were added, how do they …

[nrf fromlist][commissioner] Drop BLE connection before CASE

---

.github/workflows/release_tools.yaml

Python CHIP controller will be replaced by the chip-tool,
as a recommended controller testing tool.

[nrf noup] Replaced Python controller with chip-tool in workflow

---

src/platform/nrfconnect/OTAImageProcessorImpl.cpp

This patch adapts the code to following changes in the nrf
dfu_target module:
dfu_target_init() has now parameter for choice image pair.
dfu_target_schedule_update() API function was added.

[nrf noup] [ota-ImageProcessImpl] Align to dfu_target API changes

---

.github/workflows/release_tools.yaml

Create zip packages per achitecture rather than per build
variant (debug or release) as it's less likely that someone
download packages for two architectures on a single host.
Make the package names follow the same convention as Android
packages.

[nrf noup] Change chip-tool package names

---

config/nrfconnect/chip-module/Kconfig.defaults
src/platform/nrfconnect/CHIPPlatformConfig.h

-Fix hash size issue (grew from 240 to 244 bytes)
-Changing default to disable PSA Crypto driver for nrf_cc3xx
as it is not in use yet
-Removed CC3XX_BACKEND configuration from defaults
ref: NCSDK-13857
Signed-off-by: Frank Audun Kvamtrø <frank.kvamtro@nordicsemi.no>

matter: Update default for matter to enable nrf_oberon

---

.github/workflows/release_tools.yaml

Too old Docker image was used for release_tools workflow and chip-tool build would fail because of that.

[nrf noup] Bump release_tools workflow Docker image

---

.github/workflows/release_tools.yaml
scripts/idl/generators/java/ChipClustersCpp.jinja
src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/clusterinteraction/ClusterDetailFragment.kt
src/android/CHIPTool/app/src/main/res/layout/select_action_fragment.xml
src/controller/java/src/chip/clusterinfo/CommandParameterInfo.java
src/controller/java/templates/ClusterInfo-java.zapt
src/controller/java/templates/ClusterInfo-write-interaction.zapt
src/controller/java/templates/helper.js
src/controller/java/zap-generated/chip/devicecontroller/ClusterInfoMapping.java
src/controller/java/zap-generated/chip/devicecontroller/ClusterWriteMapping.java
src/lib/support/JniReferences.cpp

[nrf noup] [android] Fix crash on DoorLock.lockDoor command
Cluster Interaction Tool screen would crash when trying  to send a command that takes an optional argument. The reason was that optional arguments were incorrectly converted in the application and the underlying JNI layer.
[nrf noup] Build OTA Provider for Linux in release_tools
Build OTA Provider for Linux in release_tools workflow. Also, disable debug symbols for chip-tool binaries.

Fix Android crash and extend release_tools workflow

---

config/nrfconnect/chip-module/Kconfig.defaults

The nrf noup commit from sdk-zephyr will be removed, so it was
decided to set this value in the Matter samples configuration.

[nrf noup] Set NVS_LOOKUP_CACHE_SIZE in the Matter Kconfig.defaults

---

src/platform/nrfconnect/OTAImageProcessorImpl.cpp

Moves from the obsolete device label to using the device directly
Fixes build failure with zephyr upmerge
Switches from label to node
How was this tested? (at least one bullet point required)
* If unit tests were added, how do they cover this issue?
* If unit tests existed, how were they fixed/modified to prevent this in future?
* If new unit tests are not added, why not?
* If integration tests were added, how do they verify this change?
* If new integration tests are not added, why not?
* If manually tested, what platforms controller and device platforms were manually tested, and how?
* If no testing is required, why not?

[nrfconnect] Use device instead of device label for QSPI

---

config/nrfconnect/chip-module/Kconfig.defaults
config/nrfconnect/chip-module/Kconfig.features
config/nrfconnect/chip-module/Kconfig.mcuboot.defaults

Added configs allowing to enable external flash and DFU using SPI NOR for application and mcuboot images.

[nrf noup] Added support for SPI NOR external flash

---

config/nrfconnect/chip-module/Kconfig.hci_rpmsg.defaults
config/nrfconnect/chip-module/Kconfig.hci_rpmsg.root

Create configuration for hci_rpmsg image used by WiFi build targets.

[nrf noup] Prepare configuration for hci_rpmsg

---

config/nrfconnect/chip-module/Kconfig.features
config/nrfconnect/chip-module/Kconfig.mcuboot.defaults

By default PM selects QSPI external flash. In case other
backend is used the override config should be set.

[nrf noup] Selected override config for SPI external flash

---

examples/light-switch-app/nrfconnect/README.md
src/app/tests/suites/TestGroupDemoConfig.yaml

Downstreaming changes related to light switch multicast communication.
This allows usage of the simplified chip-tool command when setting up
a group communication. Also corresponding docs update.

[nrf fromtree] Update light switch doc.

---

src/platform/nrfconnect/wifi/WiFiManager.cpp

Based on #104 but using native wifi_mgmt for doing scan rather than nrx700x specific scan. Without this once https://github.com/nrfconnect/sdk-nrf/pull/8562 this is merged, then the build will broken.

Fix build wifi offapi

---

src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp
src/platform/nrfconnect/wifi/WiFiManager.cpp

The failsafe mechanism does not work correctly when attempting to connect
to WiFi with invalid network credentials and then trying to connect with valid ones.
* Reset the number of retires used when waiting for the connection.
* Remove redundant wpa_supplicant disconnect call
* Also some dead code cleanup.
Tested with `chip-tool`:
* `./chip-tool pairing ble-wifi 1 <invalid_ssid> <valid_password> 20202021 3840 --ble-adapter 0`
* wait until the failsafe is disarmed
* `./chip-tool pairing ble-wifi 1 <valid_ssid> <valid_password> 20202021 3840 --ble-adapter 0`
* result: the device was successfully commissioned to Matter via Wi-Fi

[nrf noup] Fixed the failsafe when connecting to WiFi wih invalid credentials.

---

config/nrfconnect/chip-module/Kconfig.defaults
docs/guides/nrfconnect_android_commissioning.md

Noticed Wi-Fi low-power mode causes performance issues,
at least with some APs.

[nrf noup] Disable Wi-Fi low-power mode

---

src/platform/nrfconnect/OTAImageProcessorImpl.cpp
src/platform/nrfconnect/OTAImageProcessorImpl.h
src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp
src/platform/nrfconnect/wifi/NrfWiFiDriver.h
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

The dummy WiFiNetworkIterator causes the infinite loop when reading
network attribute from networkcommissioning cluster.
Implementation of WiFiNetworkIterator.
This PR also pulls in the BDX transfer fix from the upstream.
* commissioned with `chip-tool` to Matter with WiFi backend
* run `./chip-tool networkcommissioning read networks 1 0`
* received a list with one connected network

Wi-Fi network iterator fix

---

src/platform/nrfconnect/wifi/ConnectivityManagerImplWiFi.cpp
src/platform/nrfconnect/wifi/ConnectivityManagerImplWiFi.h
src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp
src/platform/nrfconnect/wifi/NrfWiFiDriver.h
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

Switching from wpa_supplicant API to WiFi mgmt events
- Removed wpa_supplicant calls from WiFiManager and replaced them with WiFi events from wifi_mgmt.
- Removed a workaround from ConnectivityManagerImplWifi in _SetWiFiStationMode.
- Added ConnectionWorkerHandler to switch context during calling OnResult wifi connection callback.
- Removed a workaround from ConnectivityManagerImplWifi in _SetWiFiStationMode.

[nrf noup] Start using WiFi events instead of using wpa_supplicant

---

src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp
src/platform/nrfconnect/wifi/NrfWiFiDriver.h
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

We need proper security modes handling to allow our devices to connect to AP supporting various security modes.
Utilized net_mgmt API to perform scanning before the actual connection request.
By doing so, we can cache the security mode advertised by every AP in the area
and filter the interested one by SSID.
Also fixed the bug with incorrect net_mgmt events lifetime management.
Tested by commissioning the light switch app to the networks with:
* WPA2 
* open security mode
* WPA3 (tested with iPhone working as an access point)

[nrf noup] Implemented WiFi security modes handling

---

src/platform/nrfconnect/OTAImageProcessorImpl.cpp

Unblock the code for controlling QSPI NOR power state based on the state of the DFU on the device.

[nrf noup] Enter QSPI NOR deep sleep mode on nRF52, too

---

src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

Make sure the fail-safe works as expected with WiFi networking:
- disconnect when reverting the configuration
- always cleanup the provisioning data structures before connecting to avoid dummy buffer overwriting and data length issues
Tested the following scenarios manually with `chip-tool`:
**Commissioning (failure)**
1. GeneralCommissioning.ArmFailSafe
2. NetworkCommissioning.AddOrUpdateWifiNetwork
3. NetworkCommissioning.ConnectNetwork
4. DNS-SD -> failure
5. Failsafe timeout - RevertConfiguration - disconnect from tentative Wi-Fi network
**Commissioning (success)**
1. GeneralCommissioning.ArmFailSafe
2. NetworkCommissioning.AddOrUpdateWifiNetwork
3. NNetworkCommissioning.ConnectNetwork
4. DNS-SD -> success
5. [over IP] GeneralCommissioning.CommissioningComplete - disarm …

[nrf noup] WiFi fail-safe related fixes

---

config/nrfconnect/chip-module/Kconfig.defaults

NEWLIB_LIBC_NANO config has been set to n by default in Zephyr. This caused a FLASH overflow in Matter wifi samples.
To repair that, the NEWLIB_LIBC_NANO config  should be set to y by default within our configuration system.

[nrf noup] Set NEWLIB_LIBC_NANO to y as default

---

examples/all-clusters-app/nrfconnect/CMakeLists.txt
examples/all-clusters-minimal-app/nrfconnect/CMakeLists.txt
examples/light-switch-app/nrfconnect/CMakeLists.txt
examples/lighting-app/nrfconnect/CMakeLists.txt
examples/lock-app/nrfconnect/CMakeLists.txt
examples/platform/nrfconnect/util/DFUOverSMP.cpp
examples/platform/nrfconnect/util/OTAUtil.cpp
examples/platform/nrfconnect/util/include/OTAUtil.h
examples/pump-app/nrfconnect/CMakeLists.txt
examples/pump-controller-app/nrfconnect/CMakeLists.txt
examples/window-app/nrfconnect/CMakeLists.txt
src/platform/nrfconnect/BUILD.gn
src/platform/nrfconnect/ExternalFlashManager.h
src/platform/nrfconnect/OTAImageProcessorImpl.cpp
src/platform/nrfconnect/OTAImageProcessorImpl.h

The FlashHandler implementation was coupled with Matter OTAImageProcessorImpl, what resulted with the fact that it was not possible to use build other DFU mechanisms, like DFU over BT SMP without Matter OTA enabled.
Summary of changes:
* Moved FlashHandler to separate file called ExternalFlashManager
* Added ifdefs to OTAUtil that prevents from building Matter OTA dependencies while Matter OTA is disabled.
(cherry picked from commit d9936213e6714137ec49446ba6bd46c687c6d249)

[nrf fromlist] Moved FlashHandler implementation to separate file

---

src/lib/dnssd/Advertiser_ImplMinimalMdns.cpp

mDNS clients such as avahi would keep stale commissionable node service in their caches because minimal mDNS does not send "Goodbye" packets properly on service removal. That is, it attempts to send records with TTL=0 in Advertise() methods which are called after RemoveServices() which clears all allocated responders.

[nrf noup] Fix sending mDNS goodbye packets

---

src/platform/nrfconnect/DiagnosticDataProviderImplNrf.cpp

We can now use this feature in spite of statistics still not being implemented.

[nrf noup] wifi: forward the channel number and RSSI from WIFiManager

---

config/nrfconnect/chip-module/Kconfig.defaults
src/platform/Zephyr/SysHeapMalloc.cpp

* Fix build with CHIP_MALLOC_SYS_HEAP Kconfig option that replaces default malloc/free with alternatives based on Zephyr's sys_heap.
* If the default heap is used, error out if less than 16kB of RAM has been left for the heap.

[nrf noup] Minor fixes for heap usage

---

config/nrfconnect/chip-module/Kconfig.defaults

In some configurations (i.e. with BLE SMP enabled) we cannot achieve 16kB of free RAM for newlibc. 16kB was set with redundancy in mind, so we can make this requirement less strict (12kB).

[nrf noup] Decrease the minimum heap size for newlibc

---

config/nrfconnect/chip-module/Kconfig.defaults
src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp
src/platform/nrfconnect/wifi/NrfWiFiDriver.h
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

* Increase the SYSTEM_WORKQUEUE_STACK_SIZE to match supplicant needs
* Decrease the connection timeout to be lower than failsafe (35s)
* Adapt WiFiRequestStatus to follow supplicant implementation
* All of above makes the failsafe more robust
Note that the following patch in wpa_supplicant is needed to have the proper connection timeout handling:
https://github.com/nrfconnect/sdk-hostap/pull/45

[nrf noup] Wi-Fi status handling fixes

---

examples/lighting-app/nrfconnect/main/AppTask.cpp
src/app/AttributePersistenceProvider.h
src/app/BUILD.gn
src/app/DefaultAttributePersistenceProvider.cpp
src/app/DefaultAttributePersistenceProvider.h
src/app/DeferredAttributePersistenceProvider.cpp
src/app/DeferredAttributePersistenceProvider.h
src/app/server/Server.h
src/app/util/attribute-storage.cpp

* [app] Implement deferred attribute persister
Fast-changing attributes with NVM storage, such as CurrentLevel of the LevelControl cluster, may result in rapid flash wearout using the default attribute persister which stores all values immediately.
Implement a helper adapter class for the attribute persistence interface to defer writes of selected
attributes.
Use the new class in nRF Connect lighting-app for
verification.
* Code review
* Add a comment

[nrf fromtree] [app] Implement deferred attribute persister (#23366)

---

config/nrfconnect/chip-module/CMakeLists.txt

This commit updates the chip-module build configurations to define `_DEFAULT_SOURCE` when compiling Matter because it uses non-standard functions that are only available when `_DEFAULT_SOURCE` is defined.
Note that this used to be not necessary only because of a quirk in the way Newlib handles the feature test macro, which resulted in Newlib defining `_DEFAULT_SOURCE` when compiling with `-std=gnu`.
For more details, refer to the issue zephyrproject-rtos/zephyr#52739.
Signed-off-by: Stephanos Ioannidis <stephanos.ioannidis@nordicsemi.no>

[nrf noup] config: nrfconnect: Define _DEFAULT_SOURCE

---

src/platform/nrfconnect/DiagnosticDataProviderImplNrf.cpp
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

Added PHY statistics based on the Zephyr net_mgmt API (NET_REQUEST_STATS_GET_WIFI):
* multicast RX/TX
* unicast RX/TX
* beacons lost/TX
Also added MapToMatterWiFiVersionCode function to align supplicant WiFi version code with Matter world.

[nrf noup] wifi: implemented most of the Wi-Fi DiagnosticDataProvider

---

docs/guides/nrfconnect_factory_data_configuration.md
scripts/tools/nrfconnect/generate_nrfconnect_chip_factory_data.py

In the factory data script, there was no checking if a user has jsonschema module installed. That caused an error even if the user did not want to use that way of JSON validation.
Added checking a jsonschema module in python script for generating factory data and added proper information in the documentation about how to obtain jsonschema python module.

[nrf fromtree] [nrfconnect] Fix for jsonschema documentation and factory data script

---

src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

Restore the connection state which was set before requesting scan. Note that the connection was not really dropped, only the status reporting was broken.

[nrf noup] Fix the 'disconnected' status appearing after scan is issued

---

config/nrfconnect/chip-module/make_gn_args.py

Stop filtering out gdwarf-4 when passing flags from Zephyr to Matter's GN build system. Older pyelftools versions are not able to parse DWARF5 format, so ram and rom report would not be generated.

[nrf noup] Fix ram_report and rom_report

---

src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp

This fixes the misbehavior when attempting to establish a connection with the network that is not added to the networkcommissioning cluster.

[nrf noup] wifi: fixed the connection callback initialization

---

config/nrfconnect/chip-module/Kconfig.defaults

NFC lib introduced new callbacks that are not needed by the Matter samples and increase flash usage.

[nrf noup] Disabled NFC thread callback

---

config/zephyr/Kconfig
src/lib/dnssd/Advertiser_ImplMinimalMdns.cpp

In mDNS code there isn't a check that would verify if memory was allocated successfully. In case heap is too small the application will fall into hard fault due to usage of non-allocated memory.

[nrf noup] Fixed hard fault once advertising mdns records

---

docs/guides/nrfconnect_factory_data_configuration.md
scripts/tools/nrfconnect/tests/test_generate_factory_data.py
src/platform/nrfconnect/FactoryDataParser.c
src/platform/nrfconnect/FactoryDataParser.h
src/platform/nrfconnect/FactoryDataProvider.cpp
src/platform/nrfconnect/FactoryDataProvider.h

Factory data parser did not contain methods to obtain user data.
- Added two methods: GetUserData to obtain raw user data and GetUserKey to obtain a single key.
- Improved the FactoryDataParser to read and manage the user data field.
- Improved documentation.

[nrf fromtree] [nrfconnect] Added support for user data in Factory Data parser

---

config/nrfconnect/chip-module/Kconfig.defaults

Once we were hit by the net_mgmt thread stack overflow while show casing the Matter over WiFi solution in WiFi RF congested environment. Increase the default stack size of net_mgmt from 768 to 1k.

[nrf noup] Increased the default net_mgmt stack size

---

src/messaging/ReliableMessageMgr.cpp
src/messaging/ReliableMessageProtocolConfig.h

Increase the default MRP parameters for Thread devices from 300 to 800ms.

[nrf fromlist] Increase MRP intervals for Thread

---

config/nrfconnect/chip-module/Kconfig.defaults
config/nrfconnect/chip-module/Kconfig.features
config/nrfconnect/chip-module/Kconfig.hci_rpmsg.defaults

Pulled commits to improve Bluetooth LE connection configuration, enable Wi-Fi/BLE coex and enable erasing settings partition using MCUMGR command during DFU over Bluetooth LE SMP.

Wifi ble coex

---

src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

* Currently using the specific channel number does not work reliably in WiFi driver, so use the generic channel screening.
*  In the case there are many networks available, the scan result events may saturate the CHIP work queue which has lower priority then the net_mgmt and main threads. So, collect the scan results in the main thread and only ping the CHIP thread when the scan is done.

[nrf noup] wifi: scan refinements

---

config/nrfconnect/chip-module/Kconfig.defaults

Output power at the antenna port can be controlled automatically after setting MPSL_FEM_NRF21540_RUNTIME_PA_GAIN_CONTROL config.
After enabling it the user can use the
CONFIG_OPENTHREAD_DEFAULT_TX_POWER config to control OpenThread radio output power.

[nrf noup] Enable runtime PA gain control when FEM is active

---

config/nrfconnect/chip-module/Kconfig
config/nrfconnect/chip-module/Kconfig.features
src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

The WiFi connection recovery feature allows device re-scanning and re-connecting to the known WiFi network after the device's reboot and when the known SSID has not been found during the last scan. The connection recovery interval is doubled with
every occurrence to the defined maximum value and then its value depends on the maximum value +- the defined random jitter.
After restoring the connection, the Connection Recovery Interval is restored to the defined minimum value after elapsing of the defined delay to avoid frequent reconnections to a poor link quality network.

[nrf noup] [nrfconnect] Introduce the WiFi connection recovery feature

---

.github/workflows/release_tools.yaml

Android Chip Tool is no longer maintained so it must be removed from the release workflow.

[nrf noup] Remove Android Chip Tool build from release workflow

---

examples/platform/nrfconnect/util/DFUOverSMP.cpp

Commands are now registered automatically, this is no longer needed.
**DNM** until sdk-zephyr change is merged

mgmt: mcumgr: Remove command registration functions

---

config/nrfconnect/chip-module/Kconfig.defaults
config/nrfconnect/chip-module/Kconfig.hci_rpmsg.defaults
src/platform/nrfconnect/wifi/WiFiManager.cpp

* Disabled Wi-Fi/BLE coex as it was not stable and caused issues in CI tests
* Increased sockets poll and net mgmt stack to fix crash on the application boot due to no space to alloc all sockets
* Added generating kDnssdInitialized event after getting Wi-Fi
connected event to re-start mDNS server

[nrf noup] Fixed several Wi-Fi issues

---

src/platform/nrfconnect/wifi/WiFiManager.cpp

This is warning propagated to an error in the CI.

[nrf noup] Fix the unused variable error

---

src/platform/nrfconnect/wifi/WiFiManager.cpp

The Security type attribute was wrongly cast in the WiFi Manager. Used switch-case-based mapping between two enum types (Zephyr-Matter) to make sure that we properly cast between two different types.

[nrf noup] Mapped the WiFi security type from Zephyr to Matter

---

.github/workflows/release_tools.yaml

Currently, the chip-tool that is released as a part of sdk-connectedhomeip has dependency to openssl.
The issue is that Ubuntu 20.04 and Ubuntu 22.04 use different versions of OpenSSL and the version built under 20.04 does not work under 22.04 (without some hacks to install the old openssl version) and vice verse.
- Removed the dependency to the dynamic library (OpenSSL) to build Chip-Tool with the mbedTLS.

[nrf noup] Remove dependency to openssl from CHIP tool build for linux

---

src/platform/nrfconnect/wifi/WiFiManager.cpp

This comes in handy especially during tests related to TX/RX power.

[nrf noup] Extend the connection request log with RSSI

---

src/platform/nrfconnect/BUILD.gn
src/platform/nrfconnect/OTAImageProcessorImplWiFi.h
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

Added subclass of OTAImageProcessorImpl whcih implements Wi-Fi specific optimization for LPM which should be disabled during OTA due to the high throughput requirements. This allows applications to use the OTAImageProcessorImplWiFi to do the job.

[nrf noup] Support disabling Wi-Fi LPM during the OTA DFU

---

config/nrfconnect/chip-module/Kconfig.features
src/platform/Zephyr/BLEAdvertisingArbiter.cpp

Matter NUS feature allows to add of BLE Nordic UART Service and register commands which allow controlling the Matter device via BLE.
This can be useful when the device loses connection with a Matter Controller but it should be controlled in another way for e.g. a Door Lock.

[nrf noup] Provide configs for Matter NUS feature

---

config/nrfconnect/chip-module/Kconfig
src/platform/nrfconnect/FactoryDataProvider.h

Due to the smallest atomic SPU block (16k for nRF53) which can be protected we need to calculate proper offsets to include factory data partition.

[nrf noup] FactoryDataProvider: align the fprotect memory block

---

config/nrfconnect/chip-module/generate_factory_data.cmake
scripts/setup/requirements.nrfconnect.txt
scripts/tools/nrfconnect/generate_nrfconnect_chip_factory_data.py

In the factory data generation script, import spake2p.py as a module instead of starting a new process. This fixes running the script on windows. Also, update the requirements.

[nrf fromlist] [nrfconnect] Import spake2p.py as a module

---

config/nrfconnect/chip-module/Kconfig.defaults

* Changed default log level to error
* Changed WPA supplicant log levet to error. This is a workaround and it will be removed once default log levels fix to Zephyr will be merged.

[nrf noup] Changed WPA SUPP logs level to error

---

config/nrfconnect/chip-module/Kconfig.features

Some Kconfigs selected by the CHIP_DFU_OVER_BT_SMP have unmet dependencies.

[nrf noup] Fixed dependencies for CHIP_DFU_OVER_BT_SMP kconfig

---

config/nrfconnect/chip-module/Kconfig.features

We decided to work with a single BLE connection when NUS is active.

[nrf noup] Set BLE connection to 1 for NUS

---

config/nrfconnect/chip-module/Kconfig.defaults

After failing to connect to the Wi-Fi network (e.g. due to bad password) the application falls into stack overflow.
Increased the stack size to handle the connection failure properly.

[nrf noup] Fixed system workqueue stack overflow for Wi-Fi

---

config/nrfconnect/chip-module/Kconfig.features

Matter NUS should require providing a PIN code before each pairing, so we do not want to store anything in persistent storage and we should disable the Bluetooth LE bonding feature.

[nrf noup] Disable bonding for NUS

---

config/nrfconnect/chip-module/Kconfig.defaults

Limit assert information for Matter applications to file name and file number.
Seems to save around 20kB for nRF52840DK and nRF7002DK and 18k for nRF5340DK.

[nrf noup] Disable unnecessary assert information

---

src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

It was observed that sometimes WPA supplicant may stuck in the reconnection process. This change introduces a workaround and fixes for existing recovery mechanism:
* Changed is-Recovery-Aborted approach to is-Recovery-started.
* Distinguished disconnects requested by the application from the disconnects coming from the supplicant.
* Added scheduling recovery procedure if supplicant was not able to re-connect to the network for given amount of time (60 s).

[nrf noup] Introduce workaround to Wi-Fi connection recovery

---

examples/all-clusters-app/nrfconnect/main/AppTask.cpp
examples/all-clusters-app/nrfconnect/main/include/AppTask.h
examples/all-clusters-minimal-app/nrfconnect/main/AppTask.cpp
examples/all-clusters-minimal-app/nrfconnect/main/include/AppTask.h
examples/light-switch-app/nrfconnect/main/AppTask.cpp
examples/light-switch-app/nrfconnect/main/include/AppTask.h
examples/lighting-app/nrfconnect/main/AppTask.cpp
examples/lighting-app/nrfconnect/main/include/AppTask.h
examples/lock-app/nrfconnect/main/AppTask.cpp
examples/lock-app/nrfconnect/main/include/AppTask.h
examples/pump-app/nrfconnect/main/AppTask.cpp
examples/pump-app/nrfconnect/main/include/AppTask.h
examples/pump-controller-app/nrfconnect/main/AppTask.cpp
examples/pump-controller-app/nrfconnect/main/include/AppTask.h
examples/window-app/nrfconnect/main/AppTask.cpp
examples/window-app/nrfconnect/main/include/AppTask.h
src/platform/nrfconnect/BUILD.gn
src/platform/nrfconnect/DeviceInstanceInfoProviderImpl.cpp
src/platform/nrfconnect/DeviceInstanceInfoProviderImpl.h
src/platform/nrfconnect/FactoryDataParser.c
src/platform/nrfconnect/FactoryDataProvider.cpp

Rotating Device Id Unique Id was parsing wrongly in nrfconnect's factory data provider implementation.
There was also a problem, that testing Rotating Device Id UID was not being provided by Zephyr's Kconfig.
Repaired the factory_data build for nRFconnect devices.

[nrf fromtree][nrfconnect] Repair Rotating Device ID UID parsing

---

src/lib/shell/MainLoopZephyr.cpp
src/platform/Zephyr/SysHeapMalloc.cpp

The SYS_INIT() callback API changed in Zephyr and Matter code alignments were needed.

[nrf noup] Fixed SYS_INIT callback API

---

src/platform/nrfconnect/wifi/WiFiManager.cpp

The wifi_ps_config has been extended in Zephyr so this patch is need to avoid build errors.
This fixes the compilation errors from:
https://github.com/nrfconnect/sdk-nrf/pull/11079

[nrf noup] Adapt WiFiManager to the new wifi_ps_config API

---

config/nrfconnect/chip-module/Kconfig.features
src/app/clusters/door-lock-server/door-lock-server.cpp

BT_FIXED_PASSKEY cannot be added to prj_release.conf file because it causes a CMAKE warning. The config has been moved to the Kconfig.feature file.

[nrf noup] moved bt_fixed_passkey config to the features set

---

config/nrfconnect/chip-module/Kconfig.features

nRF7002 EK kconfig name changed once again, so we need to align our kconfigs to that.

[nrf noup] Fixed nrf7002 kconfig name again

---

config/common/cmake/chip_gn.cmake

This commit fixes building on Windows PowerShell by removing usage of "bash" command.

[nrf noup] use CMake command instead of bash in build script

---

config/nrfconnect/chip-module/Kconfig
src/platform/nrfconnect/CHIPDevicePlatformConfig.h
src/platform/nrfconnect/FactoryDataProvider.cpp

The unique id length is fixed to 16 B, while it should be equal to the current length of related string passed through kconfig

[nrf fromlist] Added calculating unique id lenght based on kconfig

---

config/nrfconnect/chip-module/Kconfig.features

Added enabling Wi-Fi support in Matter if nRF7002 EB is selected as a shield.

[nrf noup] Added support for new Wi-Fi dongle board.

---

config/nrfconnect/chip-module/Kconfig.defaults

[nrf noup] Turn off wpa_supplicant debug output

---

config/nrfconnect/chip-module/Kconfig.mcuboot.defaults
src/platform/nrfconnect/wifi/WiFiManager.cpp

Mcuboot requires zcbor, so enable it explicitly, otherwise the build fails with latest mcuboot.
Align with the upstream net_if API change.

[nrf noup] [nrfconnect] Upmerge fixes

---

scripts/tools/zap/generate.py

Usage of generate.py script is not possible on windows due to fcntl package available onlu on unix pyhton packages using I/O control on descriptor file is not needed on windows.
This change enhance script to use fcntl on non-window system.

[nrf noup] Fix generate zap sript on windows

---

config/nrfconnect/chip-module/Kconfig.defaults

With PSA_WANT configurations being default n then these default values are no longer needed for chip-module.
NCSDK-18031

config: nrfconnect: Remove PSA_WANT default n setting

---

src/app/clusters/door-lock-server/door-lock-server.cpp
src/app/clusters/door-lock-server/door-lock-server.h

This change allows an application to register custom handling
used when the device leaves the fabric.

[door-lock] extend the OnFabricRemoved delegate with custom callback

---

src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp

After the API change, there should not be cast to uint16_t in the otLinkSetCslPeriod function anymore.

[nrf noup] Repair wrong casting for CSL period setting

---

config/nrfconnect/chip-module/Kconfig
config/nrfconnect/chip-module/Kconfig.defaults

This PR includes three commits:
- Disabled BLE GATT Cache (getting 3k in Release build)
- Disabled Shell for OpenThread and HWINFO, leaving just Matter Shell (getting almost 47k in Debug build)
- Enabled erasing NVS by default during factory reset

Clean-up default KConfigs

---

config/nrfconnect/chip-module/generate_factory_data.cmake

We should try to find Python3 instead of Python within Cmake scripts.

[nrf noup] Align finding Python3 executable to NCS requirements.

---

config/nrfconnect/chip-module/Kconfig

This PR enables:
- Support for Factory Data for each build.
- Merging the generated factory data set with firmware.
- Generation onboarding codes to the build directory.

[nrf noup] Enable Factory Data by default for all samples in NCS

---

docs/guides/nrfconnect_examples_cli.md
src/lib/shell/commands/Stat.cpp

1. Rename "top" command to "peak" as the latter better describes the purpose.
2. Add documentation for stat commands.

[nrf noup] [shell] Add documentation for stat commands

---

config/nrfconnect/chip-module/Kconfig.defaults

Enable minimal shell configuration to save some ROM (~6.5k) and RAM .

[nrf noup] Enable minimal configuration of Shell

---

src/platform/nrfconnect/Reboot.cpp

Recently the mechanism of nRF52 reboot type retention which is used in Matter has been deprecated in Zephyr and can be only bring back by a dedicated KConfig. Another solution (chosen) is to explicitly store boot reason in the retention registers for both nRF52 and nRF53.
Reference Zephyr PR:
https://github.com/nrfconnect/sdk-zephyr/commit/f79a08d6c0fed793a1b86af70dcb941dd67e63d9
Another solution could be to leave the Reboot and enable the `NRF_STORE_REBOOT_TYPE_GPREGRET` KConfig but the behavior will be the same. Anyway, I think we should migrate to the suggested retention mechanism (please see KRKNWK-17601).

[nrf noup] Fixed boot reason for nRF52

---

examples/all-clusters-app/nrfconnect/main/AppTask.cpp
examples/all-clusters-minimal-app/nrfconnect/main/AppTask.cpp
examples/light-switch-app/nrfconnect/main/AppTask.cpp
examples/lighting-app/nrfconnect/main/AppTask.cpp
examples/lock-app/nrfconnect/main/AppTask.cpp
examples/platform/nrfconnect/util/OTAUtil.cpp
examples/platform/nrfconnect/util/include/OTAUtil.h
examples/pump-app/nrfconnect/main/AppTask.cpp
examples/pump-controller-app/nrfconnect/main/AppTask.cpp
examples/window-app/nrfconnect/main/AppTask.cpp
src/platform/nrfconnect/OTAImageProcessorImpl.cpp
src/platform/nrfconnect/OTAImageProcessorImpl.h

The nRF5340 target requires 4kB of FPROTECT block size (SPU limitation) and after making a restriction for the factory data partition the new image cannot be confirmed after the OTA update finishes. Due to that, we need to confirm the current OTA image before factory data initialization.
To do it we should allow confirming the image in the other place rather than during posting the OTAStateChange event and then we should inform the image processor of the confirmation status.

[nrf fromtree][nrfconnect] [OTA] Confirm the new image in the app init.

---

config/nrfconnect/chip-module/Kconfig.defaults

Increased CONFIG_NET_SOCKETS_POLL_MAX from 4 to 6, as otherwise it resulted in bus fault during connection.

[nrf noup] Increased number of net sockets poll max

---

src/app/chip_data_model.cmake
src/app/chip_data_model.gni
src/app/zap_cluster_list.py

Original contribution: https://github.com/project-chip/connectedhomeip/pull/27886
zap_cluster_list.py raises an error when the ZAP file enables a cluster that is not implemented in the SDK. This forces users to patch the SDK in order to use custom, vendor-specific clusters.
Add EXTERNAL_CLUSTERS argument to chip_configure_data_model() CMake function that takes a list of external cluster names for which the default implementation should not included nor required.
Usage example:
```
chip_configure_data_model(app
INCLUDE_SERVER
ZAP_FILE lock-app.zap
EXTERNAL_CLUSTERS BASIC_INFORMATION_CLUSTER MY_CUSTOM_CLUSTER
)
```
Replace the existing zap_clusters_with_custom_implementation argument of chip_data_model() GN template with new one: external_clusters. The previous argument took a list of …

[nrf fromtree] [app] Allow to define external clusters in chip_data_model.*

---

src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp

Enhance attaching to Thread by verifying if the current dataset is the same as provided. 
In current solution implementation will not reset the Thread interface while the 
dataset are equal to the active dataset.

[nrf noup] Enhance/Optimize attach to thread network

---

config/nrfconnect/chip-module/Kconfig.defaults
config/nrfconnect/chip-module/Kconfig.features
examples/all-clusters-app/nrfconnect/main/AppTask.cpp
examples/all-clusters-app/nrfconnect/main/include/AppTask.h
examples/all-clusters-minimal-app/nrfconnect/main/AppTask.cpp
examples/all-clusters-minimal-app/nrfconnect/main/include/AppTask.h
examples/light-switch-app/nrfconnect/main/AppTask.cpp
examples/light-switch-app/nrfconnect/main/include/AppTask.h
examples/lighting-app/nrfconnect/main/AppTask.cpp
examples/lighting-app/nrfconnect/main/include/AppTask.h
examples/lock-app/nrfconnect/main/AppTask.cpp
examples/lock-app/nrfconnect/main/include/AppTask.h
examples/platform/nrfconnect/util/include/FabricTableDelegate.h
examples/pump-app/nrfconnect/main/AppTask.cpp
examples/pump-app/nrfconnect/main/include/AppTask.h
examples/pump-controller-app/nrfconnect/main/AppTask.cpp
examples/pump-controller-app/nrfconnect/main/include/AppTask.h
examples/window-app/nrfconnect/main/AppTask.cpp
examples/window-app/nrfconnect/main/include/AppTask.h

Cherry-pick from the upstream PR.
Users can decide now what should happen after removing the last fabric:
- Do nothing.
- Erase the saved network credentials (Thread/WI-FI).
- Erase the saved network credentials and start Bluetooth LE advertising.
- Erase the saved network credentials and reboot the device.

[nrf fromtree][nrfconnect] Added erasing network credentials after last fabric removal

---

config/nrfconnect/chip-module/Kconfig.defaults

... to match the maximum number of IPv6 addresses per interface.
Zephyr ipv6_nbr implementation requires the given address to have a matching prefix set on the interface. Otherwise, the default router is used for sending neighbor advertisement and as a result, in case there are multiple routers in the network, the packet can be sent to the invalid interface (not the one which issued neighbor solicitation).
The detailed analysis of the issue can be found in KRKNWK-17318.

[nrf noup] Increase the maximum number of prefixes

---

config/nrfconnect/chip-module/Kconfig
config/nrfconnect/chip-module/Kconfig.defaults

By default, use the lookup cache hash function optimized for NVS used as the settings backend. This assumes that a user application uses Zephyr settings API and does not write to the NVS directly.
Corresponding change: https://github.com/nrfconnect/sdk-zephyr/pull/1263

[nrf noup] [nrfconnect] Enable NVS lookup cache settings optimization

---

scripts/setup/nrfconnect/get_zap.py

The names of ZAP release bundles were changed. This needs to
be reflected in the script for getting the proper ZAP version, otherwise
the ZAP packages cannot be automatically downloaded on the host.

Fixed zap assets names

---

config/nrfconnect/chip-module/Kconfig.defaults

This aims to keep memory footprint after this config is enabled by default in NCS.

[nrf noup] Disable nRF70 driver logs verbosity by default

---

src/app/reporting/Engine.cpp
src/app/util/attribute-storage.cpp

When we set a low value to the minimum subscription interval for subscription for the PartList attribute of the Description cluster, and then remove a dynamic endpoint the related bitmask may change after reporting it to a controller.
The controller receives the old number of endpoints and does not update it within the following subscriptions until the next change of the PartList attribute occurs.
To resolve the issue the endpoint bitmask should be cleared before reporting the PartList attribute of the Descriptor cluster to avoid race conditions.
[nrf] -> There is an old API and there is a bitmask operation instead of the method Clear!

[nrf fromlist] Clear endpoint bitmask before reporting the PartList attribute

---

config/nrfconnect/chip-module/Kconfig.defaults
config/nrfconnect/chip-module/Kconfig.hci_rpmsg.defaults
config/nrfconnect/chip-module/Kconfig.multiprotocol_rpmsg.defaults

There were some interoperability issues discovered due to BLE PHY dynamic changes from 1M to 2M. The 2M was disabled to ensure the interoperability with some of the BT controllers.

[nrf noup] Disabled BLE 2M PHY due to interoperability issues

---

config/nrfconnect/chip-module/Kconfig.features
docs/guides/nrfconnect_factory_data_configuration.md
examples/all-clusters-app/nrfconnect/main/include/AppTask.h
examples/all-clusters-minimal-app/nrfconnect/main/include/AppTask.h
examples/light-switch-app/nrfconnect/main/include/AppTask.h
examples/lighting-app/nrfconnect/main/include/AppTask.h
examples/lock-app/nrfconnect/main/include/AppTask.h
examples/platform/nrfconnect/util/include/FabricTableDelegate.h
examples/pump-app/nrfconnect/main/include/AppTask.h
examples/pump-controller-app/nrfconnect/main/include/AppTask.h
examples/window-app/nrfconnect/main/include/AppTask.h

In some cases, a last fabric removal action should be delayed to avoid race conditions and allow the device to finish all currently running tasks.
To control the delay use the
CONFIG_CHIP_LAST_FABRIC_REMOVED_SCHEDULE_TIME kconfig. By default, it has been set to 500 ms.

[nrf fromlist] [nrfconnect] Add a delay to last fabric remove action

---

config/nrfconnect/chip-module/Kconfig.defaults

Recently some new Wi-Fi logs were enabled by default. These need to be disabled to decrease memory footprint.

[nrf noup] Disabled Wi-Fi logs to save flash

---

config/nrfconnect/chip-module/Kconfig.defaults
config/nrfconnect/chip-module/Kconfig.features

This commit increases the number of TX Tokens to the previous value of 10 to prevent RPU stalls.
Additionally, it was observed that a 500ms delay before executing a factory reset is too small for certain situations on Wi-Fi. This commit also increases this delay to 1s.
I run 200 commissionings with few controlling commands on 2GHz and 5GHz Wi-Fi networks, and with included changes I have not observed permanent data stall or failing `unpair` command. Without it, I observed both.

[nrf noup] Increase stability of Wi-Fi LPM operations

---

config/nrfconnect/chip-module/CMakeLists.txt
src/lib/shell/MainLoopZephyr.cpp
src/platform/Zephyr/SysHeapMalloc.cpp

[Zephyr] Fix sys_heap malloc build with LTO
[nrfconnect] Do not link libCHIPShell.a with --whole-archive

LTO build fixes

---

src/platform/nrfconnect/Reboot.cpp

Now the API to manage GPREGRET register is unified for all devices having one or more GPREGRET entries.
This PR is related to nrfx API change introduced in this PR: https://github.com/nrfconnect/sdk-zephyr/pull/1343

[nrf fromlist] [nrfconnect] Align nrf_power calls to new scheme

---

src/app/clusters/door-lock-server/door-lock-server.cpp
src/app/clusters/door-lock-server/door-lock-server.h

In case we use a custom handling lock credential we need a mechanism that allows us to handle a lock operation error when the wrong credential has been provided.
Added handling local lock operation error to emit LockOperationEvent and call HandleWrongCodeEntry.

[nrf fromtree] app: clusters: Add handling a local lock operation error

---

src/app/chip_data_model.cmake
src/app/chip_data_model.gni
src/app/clusters/door-lock-server/door-lock-server.cpp
src/app/clusters/door-lock-server/door-lock-server.h
src/app/zap_cluster_list.py

List of cherry-picked commits:
https://github.com/nrfconnect/sdk-connectedhomeip/commit/58419239f9208017a20b76e379397cd17ebcb71a
https://github.com/nrfconnect/sdk-connectedhomeip/commit/66a5f333cc7a31656958982c80a81aaefa4b8216
https://github.com/nrfconnect/sdk-connectedhomeip/commit/e89b1238af043d4d7df79fb3fbcc7c2e3f28f658
Reason: these should have been ported to the `master` branch prior to the `v2.5.0` tag.
The `master` will be populated with these patches as a result of upcoming upmerge.

Update 2.5-branch with relevant 2.4-branch cherry-picks

---

src/app/clusters/door-lock-server/door-lock-server.cpp

...to the HandleLocalLockOperationError method
We cannot assume that the valid user index is provided
in case of the invalid credential.
In fact, the spec in 5.2.5.4.4 says that UserIndex SHALL be null
if there is no user id that can be determined for the given
operation source.

[nrf fromlist] [door-lock] Fix the crash when providing null-ed user index

---

src/app/CommandHandler.cpp
src/app/CommandHandler.h

Pulled fix contributed to Matter upstream and fixing commands handling for the groupcast communication:
The command handler status is added for the response purposes even in case of invoking commands targeted to the group. In case of using more than one endpoint on a single Matter node that was added to the same group, it leads to the application crash. The direct reason is a state check, that succeeds only for the first endpoint and fails for the subsequent calls.
Added a new state flag, which informs if the command that is currently handled origins from groupcast communication or not. In case of targeting the group, application returns prematurely and do not try to add status.

[nrf fromlist] Fix handling command handler status for group messages

---

config/nrfconnect/chip-module/Kconfig.defaults

Removed custom max data size configuration, which lead to failures during commissioning with 4th or 5th controller.

[nrf noup] Increased Wi-Fi max data size to fix commissioning fails

---

config/nrfconnect/chip-module/Kconfig.defaults

Removed overwriting mbedTLS configs handled by OpenThread Kconfig:
* MBEDTLS_TLS_LIBRARY
* MBEDTLS_ECJPAKE_C
Are handled in sdk-nrf repository in `subsys/net/openthread/Kconfig` They should not be overwritten by Matter config.
(cherry picked from  https://github.com/project-chip/connectedhomeip/commit/4922ea669a2397bf19a666d3ada9e6e06adc7529)

[nrf fromtree] [nrfconnect] Removed overwriting mbedTLS configs handled by OT (#30577)

---

src/platform/Zephyr/ConfigurationManagerImpl.cpp
src/platform/Zephyr/InetUtils.cpp
src/platform/Zephyr/InetUtils.h
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

Find the Wi-Fi interface at the Wi-Fi manager initialization and use that interface instead of the default interface when calling Wi-Fi management functions.

[nrf noup] Make Wi-Fi manager use Wi-Fi interface only

---

src/inet/UDPEndPointImplSockets.cpp
src/inet/UDPEndPointImplSockets.h
src/platform/Zephyr/ThreadStackManagerImpl.cpp
src/platform/nrfconnect/BUILD.gn
src/platform/nrfconnect/ConnectivityManagerImpl.cpp
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/telink/ThreadStackManagerImpl.cpp

Move the platform handler for joining and leaving a multicast group to ConnectivityManagerImpl to support Matter stack on a system with multiple network interfaces (Thread + Wi-Fi). Previously, both Thread and WiFi would try to register their handler but only one of them would win.

[nrf noup] [nrfconnect] Move handler for joining/leaving mcast group

---

src/platform/Zephyr/BLEManagerImpl.cpp
src/platform/Zephyr/BLEManagerImpl.h

Matter BLEManager handles all BT connect and disconnect callbacks no matter if these are Matter related ones or not. It collides with other not Matter-related services that trigger Matter CHIPoBLE service advertising changes. Added role check that allows to at least drop all callbacks related to BT central role.

[nrf noup] Added check to drop handling callbacks for BT central

---

config/nrfconnect/chip-module/CMakeLists.txt
src/crypto/BUILD.gn
src/crypto/PSASpake2p.cpp
src/crypto/PSASpake2p.h
src/crypto/crypto.gni
src/protocols/secure_channel/PASESession.h

Implement Matter's SPAKE2+ protocol using PSA crypto API. Use the PSA implementation in PASE session for nRF Connect platform.
**Note:** The implementation can't be used without changes in PSA crypto driver listed in NCSDK-23835.

[crypto] Add PSA SPAKE2+ implementation

---

config/nrfconnect/chip-module/Kconfig.defaults

This commit disables WPA_SUPP_ADVANCED_FEATURES. This change gives 25k free space of wifi app.

[nrf noup] WPA supplicant advanced features disabled

---

config/zephyr/Kconfig
src/app/DeferredAttributePersistenceProvider.cpp
src/darwin/Framework/CHIP/MTRBaseDevice.mm
src/lib/support/ScopedBuffer.h
src/platform/Zephyr/SysHeapMalloc.cpp

ScopedMemoryBuffer's Release() method was used instead of Free(). Add CHECK_RETURN_VALUE annotation to the Release() method to prevent from making such a mistake in the future.
Also, add a mechanism to trace memory allocations.

[nrf fromlist] [app] Fix DeferredAttributePersister memory leak

---

config/nrfconnect/chip-module/Kconfig
src/crypto/CHIPCryptoPALPSA.h
src/platform/nrfconnect/CHIPPlatformConfig.h
src/platform/nrfconnect/FactoryDataParser.c
src/platform/nrfconnect/FactoryDataParser.h
src/platform/nrfconnect/FactoryDataProvider.cpp
src/platform/nrfconnect/FactoryDataProvider.h

We need a mechanism to move the DAC private key from the factory data set to PSA ITS NVM storage during the first boot of the device.
Then the DAC private key must be removed from the factory data set and protected by overwriting.
In this commit:
- Added a method to FactoryDataProvider for moving and removing DAC from the factory data set.
- Aligned the SignWithDeviceAttestationKey method to work with stored DAC private key in ITS NVM instead of raw data.
- Extended the FactoryDataParser module by the Serialize method that is responsible for creating CBOR-formated factory data from the FactoryData struct.
- Added a Kconfig to define the PSA ITS NVM offset for Matter keys.
- x509 MBedTLS support seems to be not needed anymore - we can disable it and save ~20kB of FLASH.
- Prevent the DAC …

[nrf noup] Move DAC priv key from Factory Data to PSA ITS

---

src/platform/Zephyr/BLEAdvertisingArbiter.cpp
src/platform/Zephyr/BLEAdvertisingArbiter.h
src/platform/Zephyr/BLEManagerImpl.cpp

Currently the Zephyr BLE Manager rotates Bluetooth addresses on every boot and it does this by creating new Bluetooth identity. Because of that the Zephyr stack does not create default Bluetooth ID, which is required e.g. for the bonding purposes.
Added creating two separate Bluetooth identities - for the Matter service advertising and for the bonding purposes.

[nrf noup][zephyr] Enabled support for bonding in the BLEManager

---

src/platform/nrfconnect/FactoryDataProvider.h

... to facilitate dynamic assignments of FactoryDataProvider concrete types to to the generic pointer.

[nrf noup] [nrfconnect] Added FactoryDataProviderBase

---

src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.hpp

OpenThread applications would crash upon receiving an empty DNS TXT record. The reason was that the code for copying OT DNS service info object into Matter DnssdService object would not initialize the TXT entry count in the latter object in such a case.
In the reported case, the Matter stack was presented an empty TXT record because OpenThread's DNS client received a TXT record with TTL 0 and it discarded its contents. Nevertheless, the issue could be reproduced by publishing Matter service without TXT entries and kicking off DNS query.
1. Initialize the TXT entry and subtype count properly in all scenarios.
2. Do not even process the service info object if an error was returned by OpenThread before.
3. Extract some boilerplate to a separate function to improve readability.

[nrf fromtree][OpenThread] Harden DNS record parsing

---

src/platform/Zephyr/CHIPDevicePlatformEvent.h

Currently the CHIPDevicePlatformEvent depends on the SystemPacketBuffer which is included in the
CHIPDeviceEvent.h too late.
The problem is silently worked around in the application when the <platform/PlatformManager.h> include is preceded by other headers that pull in SystemPacketBuffer.h, but we need a proper fix.

[nrf noup] [zephyr] Fix CHIPDevicePlatformEvent.h include dependencies

---

src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

The Wi-Fi device does not update mDNS queries after obtaining new IPv6 GUA prefix, so for some time after assigning prefix, the Thread Border Routers still use cached link-local address, which is not routable.

[nrf noup] Added DNS server refresh after adding new IPv6 prefix

---

src/app/DeferredAttributePersistenceProvider.cpp
src/darwin/Framework/CHIP/MTRBaseDevice.mm
src/lib/support/ScopedBuffer.h
src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

Pulled cherry-picks for the nRF Connect SDK v2.5.2 release

Pulled fixes for the v2.5.2 

---

src/platform/nrfconnect/wifi/WiFiManager.cpp

Wi-Fi stack recently introduced a check for valid band value and the default value of 0 (memset) means only 2.4GHz, so, 5GHz Wi-Fi associations will fail.
Fix the default to Unknown to scan all supported bands.
Fixes KRKNWK-18035.
Signed-off-by: Chaitanya Tata <Chaitanya.Tata@nordicsemi.no>
(cherry picked from commit e8e30f97a33163ebcacc6142804e05a340bc9582)

[nrf noup] wifi: Fix 5GHz association

---

src/platform/Zephyr/ConfigurationManagerImpl.cpp

This commit fix a problem with thread activity interrupting factory reset. This activity used to led to “Factory reset fail: -6”. Writing to cleared nvm flash pages caused the problem.

[nrf noup] Lock thread stack before factory reset

---

config/nrfconnect/chip-module/Kconfig.defaults

Force the default value of the libc heap to remain dynamic instead of propagating 30k of pre-reserved pool from wpa_supplicat. Also align the sys_heap pool to match the default Wi-Fi heap size.
This shall be pulled a part of https://github.com/nrfconnect/sdk-nrf/pull/13931.

[nrf noup] Align heap configuration to Wi-Fi needs

---

config/nrfconnect/chip-module/CMakeLists.txt
config/nrfconnect/chip-module/Kconfig.defaults

MBEDTLS_USER_CONFIG_FILE has been replaced with MBEDTLS_PSA_CRYPTO_CONFIG_FILE and MBEDTLS_PSA_CRYPTO_USER_CONFIG_FILE. This commit updates Matter's CMakeLists to reflect this.
Needed for upmerge https://github.com/nrfconnect/sdk-nrf/pull/13662

[nrf noup] Update Mbed TLS config file defines

---

src/platform/nrfconnect/FactoryDataParser.c
src/platform/telink/FactoryDataParser.c

New parameter to ZCBOR_STATE_D()

[nrf noup] nrfconnect/telink: Adapt to zcbor 0.8.1

---

src/platform/Zephyr/BLEManagerImpl.cpp
src/platform/Zephyr/BLEManagerImpl.h

* allow BLE advertising restarts in case of failures
* which can be triggered by calling SetBLEAdvertisingEnabled(true) ConnectivityMgr public API from the application code
* do not register CHIPoBLE GATT services when the advertising cannot be started
* this allows the disconnection handler to filter out non-Matter BLE connections that were terminated
* fix possible underflow of connection counters

[nrf noup] [zephyr] Allow BLE advertising restarts

---

config/nrfconnect/chip-module/Kconfig.defaults
config/zephyr/chip-module/Kconfig.defaults

Disable synchronous printk to avoid blocking IRQs which may affect time sensitive components (like 15.4 radio).

[nrf noup] [nrfconnect] [zephyr] Disable synchronous printk

---

src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

The previous commit has been merged too fast and caused regression on nightly tests.
We decided to not check the interfaces.
This reverts commit 324ff7699e65c2120af6a6c665b6ccf63cda71d9.

Revert "[nrf fromlist][nrfconnect] Add checking of Wi-Fi supplicant and Interface"

---

config/nrfconnect/chip-module/Kconfig
config/nrfconnect/chip-module/generate_factory_data.cmake
docs/guides/nrfconnect_factory_data_configuration.md
scripts/tools/nrfconnect/generate_nrfconnect_chip_factory_data.py

Refactored Factory Data Support:
- Added some useful tips to the Factory Data Guide.
- The SPAKE2+ verifier is now generated by default with each build.
- The Test Certification Declaration can now be generated separately and no longer requires the generation of the DAC and PAI certificates.
- The Rotating Device ID Unique ID can be used and generated only if the CONFIG_CHIP_ROTATING_DEVICE_ID is set to 'y'.

[nrf fromlist][nrfconnect] Refactor of the factory data support

---

config/nrfconnect/chip-module/Kconfig.defaults

This commit sets the default kconfigs if the WiFi FW patch on external flash is enabled.
This is not the final solution, for now for testing purposes only.

[nrf noup] Adapt Matter SDK to te WiFi FW patch on external flash

---

src/app/clusters/door-lock-server/door-lock-server.cpp

This fixes the uninitialized variable warning appearing when compiling the door lock app.

[nrf noup] Fix the build warning in door-lock-server

---

src/app/CommandHandler.cpp

CommandHandler uses VerifyOrDie when adding a status to be sent to the requestor. If the device runs out packet buffers and CommandHandler fails to allocate a packet for the status, the device crashes.
Triggering the crash requires many commands to arrive in the device around the same time, which is probably rare but possible.

[nrf fromlist] [app] Do not crash if CommandHandler fails to allocate packet

---

config/nrfconnect/chip-module/Kconfig

Currently, there is an issue with persistent subscriptions when multiple controllers create subscriptions.

[nrf noup] Select Experimental for persistent subscriptions

---

src/app/clusters/network-commissioning/network-commissioning.cpp
src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp
src/platform/nrfconnect/wifi/NrfWiFiDriver.h
src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

This PR fixes few issues with Network Commissioning cluster on Wi-Fi platform.
Please review commit by commit.
**[nrf noup] Fix handling of LastNetworkID in Wi-Fi driver**
This commit ensures that `LastNetworkID` attribute is not null, not only after `ConnectNetwork` command is issued, but also in case the connection is established after resboot or after connection is lost.
`[1709852472.587357][369591:369593] CHIP:TOO:   LastNetworkID: 536368726F64696E676572205761766573203547`
**[nrf noup] Do not clear Last Network ID and Connection Error after scan**
This bug is already fixed upstream for Matter 1.3. This fixes the issue where `LastNetworkID` attribute is cleared after `ScanNetworks` command is completed.
**[nrf noup] Fix various Wi-Fi issues with error code handling**
This commit …

[nrf noup] fix various issues with Network Commissioning cluster on Wi-Fi

---

scripts/setup/nrfconnect/get_zap.py

Fix updating get_zap.py script, which ensure zap will work on the MacOs systems.

[nrf noup] Fix zap instalation for MacOs

---

src/app/chip_data_model.cmake

The necessary change was reverted during the last upmerge. Without this fix, the external cluster injection does not work.
This patch was already applied on the 2.6.0-branch.

[nrf noup] Fix the external cluster injection mechanism

---

config/nrfconnect/app/enable-gnu-std.cmake
config/nrfconnect/chip-module/Kconfig.defaults
src/platform/nrfconnect/SystemPlatformConfig.h

Fixes:
* The recvmsg() is now implemented natively in Zephyr, so we are not supposed to define a custom one.
* D_SYS__PTHREADTYPES_H_ should not be forced (otherwise pthread definitions are not pulled in)
* NEWLIB_LIBC must be selected implicitly (it's no longer selected by wpa_supplicant)

Zephyr 01-03-2024 upmerge fixes

---

config/nrfconnect/chip-module/Kconfig.defaults
config/nrfconnect/chip-module/Kconfig.features

Enabled the full SHELL option when memory profiling is enabled.

[nrf fromlist][nrfconnect] Improve CHIP_MEMORY_PROFILING config

---

config/nrfconnect/chip-module/generate_factory_data.cmake
docs/guides/nrfconnect_factory_data_configuration.md
scripts/tools/nrfconnect/generate_nrfconnect_chip_factory_data.py

The factory_data.hex file is not generated as an intermediate product of factory generation process. In result, factory generation works only if merging with firmware is used or scripts are manually invoked.
Added optional --size and --offset arguments to
generate_nrfconnect_chip_factory_data.py script that results in calling nrfconnect_generate_partition.py internally. It solves an issue and additionally simplifies manual generation process (if selected).

[scripts] Fixed nrfconnect factory generation scripts

---

config/nrfconnect/chip-module/Kconfig
config/nrfconnect/chip-module/generate_factory_data.cmake
docs/guides/nrfconnect_factory_data_configuration.md
src/platform/nrfconnect/FactoryDataProvider.cpp
src/platform/nrfconnect/FactoryDataProvider.h

Added support for platforms not built using PM. This commit includes fixes only firmware implementation and does not include cmake changes for factory data generation.
- Allow to merge the factory data .hex file with the firmware's .hex file when the partition manager is not available.

[nrfconnect] Improved generation of factory data

---

.gitignore
scripts/west/west-commands.yml
scripts/west/zap_common.py
scripts/west/zap_generate.py
scripts/west/zap_gui.py

[nrf noup] Add custom west commands to ease ZAP usage
Add "zap-gui" west command that runs ZAP GUI to edit
the requested ZAP file.
Add "zap-generate" west command that generates the cluster
code out of the requested ZAP file.
Both commands verify if a correct version of ZAP package
is installed in .zap-install directory in the Matter SDK
module, and update the installed version accordingly.
The commands also try to find the ZAP file in the current
directory if the ZAP file path is not explicitly provided.

[nrf noup] Add custom west commands to ease ZAP usage

---

src/platform/nrfconnect/FactoryDataProvider.cpp
src/platform/nrfconnect/FactoryDataProvider.h

We need to have support for factory data when the partition manager is enabled but there is no support for QSPI external flash.

[nrf toup] [nrfconnect] Disable External FD if QSPI NOR is not available

---

config/nrfconnect/chip-module/Kconfig.defaults
config/nrfconnect/chip-module/Kconfig.features
config/nrfconnect/chip-module/Kconfig.mcuboot.defaults

Removed the defaults from Kconfig.mcuboot.defaults configuration that should not be set there:
* BOOT_ENCRYPT_X - are configs without a prompt, so it should not be modified outside of the mcuboot module
* SPI_NOR and NORDIC_QSPI_NOR - are set based on the device tree configuration, so we should not set it, as it may lead to configuration and dts mismatch.

[nrf toup][nrfconnect] Fixed mcuboot default configuration

---

src/platform/nrfconnect/wifi/WiFiManager.cpp

Wi-Fi unicast tx/rx counters were calculated based on a wrong values, what could lead to getting negative results.
Recent changes allow to use dedicated unicast structure field instead of obtaining the values based on calculation.

[nrf toup][nrfconnect] Fixed calculation of Wi-Fi unicast counters

---

src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.hpp
src/platform/Zephyr/ConfigurationManagerImpl.cpp

Apart from disabling Thread, and erasing Persistent Info, we should disable the IPv6 interface as well and block receiving further packets.
Otherwise, if we don't reboot the device after erasing Thread persistent data, we can get a packet and as a result, it causes an assert during processing AES_ECB
(because crypto keys have been removed).
cherry-picked from: 416f6a315f286a242e78048039b6525cafaabd74

[nrf fromtree][OpenThread] Disable IPv6 interface during erasing persistent info. (#33170)

---

config/nrfconnect/chip-module/CMakeLists.txt
config/nrfconnect/chip-module/generate_factory_data_sysbuild.cmake
config/zephyr/ota-image_sysbuild.cmake

Adds initial WIP sysbuild files
> !!!!!!!!!! Please delete the instructions below and replace with PR description
>
> If you have an issue number, please use a syntax of
> `Fixes #12345` and a brief change description
>
> If you do not have an issue number, please have a good description of
> the problem and the fix. Help the reviewer understand what to expect.
>
> Make sure you delete these instructions (to prove you have read them).
>
> !!!!!!!!!! Instructions end

config: Add initial sysbuild files

---

scripts/west/zap_common.py
scripts/west/zap_generate.py
scripts/west/zap_gui.py

Followup from the feedback during the command presentation:
1. If multiple ZAP files are detected in the given location, ask a user to choose the one to edit.
2. Allow to provide a Matter SDK path to enable using the commands with the upstream repo.

[nrf noup] ZAP west command improvements

---

src/darwin/Framework/chip_xcode_build_connector.sh
src/platform/BUILD.gn

Cherry-picked commit that should fix building Matter on Windows system.

Fix building on Windows

---

src/platform/nrfconnect/Reboot.cpp

Provided a workaround for power reason for nrf54h20 since it is not available yet.

[nrf noup] Power nRF54H20 workaround.

---

config/nrfconnect/chip-module/Kconfig.defaults

This commit enables MBEDTLS_AES_ONLY_128_BIT_KEY_LENGTH for Matter over Wi-Fi to optimize flash usage (~0.4k).

[nrf toup] Enable MBEDTLS_AES_ONLY_128_BIT_KEY_LENGTH config

---

config/nrfconnect/chip-module/Kconfig.defaults

Remove setting `CONFIG_FPU` to `y` by default as OpenThread libraries are now build without FPU support.

[nrf toup] Disable `CONFIG_FPU` by default to align with OT libraries

---

src/platform/nrfconnect/wifi/WiFiManager.cpp

There is a missing network band parameter in the scan response, and due to that the `networkcommissioning scan-networks` command shows 0 as the band field for all found networks.
Fixes: KRKNWK-19105

[nrf toup] Fix missing network band in scan response.

---

.github/workflows/release_tools.yaml

This fixes the chip tools build workflow.

[nrf noup] ci: update the docker image

---

config/nrfconnect/chip-module/Kconfig
config/nrfconnect/chip-module/Kconfig.features

Added the new CHIP_SUIT config to enable all required dependencies for SUIT. Added SUIT for CHIP_DFU_OVER_BT_SMP to automatically enable SUIT module and BT SMP for nRF54H20.

[nrf noup] Add SUIT to the Matter configuration

---

config/nrfconnect/chip-module/Kconfig.defaults
src/platform/nrfconnect/OTAImageProcessorImpl.cpp
src/platform/nrfconnect/OTAImageProcessorImpl.h

Modified the OTAImageProcessorImpl to use dfu target multi image only in case of using the mcuboot bootloader and to use dfu target in case of using suit.

[nrf toup][nrfconnect] Added support for Matter OTA using SUIT

---

src/platform/nrfconnect/ConnectivityManagerImpl.h

* Added new API for generic IPv6 connectivity checks
* This patch allows the application layer to limit the amount of pre-processor logic (CONFIG_NET_L2_OPENTHREAD/CONFIG_CHIP_WIFI) needed to configure the

[nrf toup] [nrfconnect] Implement IPv6 agnostic L2 network state getters

---

config/nrfconnect/chip-module/Kconfig.defaults
config/nrfconnect/chip-module/Kconfig.features

Enabled settings shell configuration and increased shell command
buffer size when `CHIP_MEMORY_PROFILING` is enabled to allow
reading and writing settings using shell.

[nrf toup][nrfconnect] Added support for settings shell in mem profiling

---

src/platform/nrfconnect/wifi/WiFiManager.cpp

This might help when debugging the WiFi connection failures.
manfiest-PR-skip

[nrf toup] [nrfconnect] Added log for the WiFi connection failure

---

src/platform/nrfconnect/ExternalFlashManager.h

Make `ExternalFlashManager` a singleton and move `DoAction` implementation to `ExternalFlashManager.cpp`

[nrf toup][nrfconnect] Refactor ExternalFlashManager

---

config/nrfconnect/chip-module/Kconfig.defaults

Whien LIT is enabled, higher workqueue stack size is required when entering active mode.

[nrf toup] [nrfconnect] Increase workqueue stack size for LIT

---

src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp

Don't pass uninitialized WiFiInfo object to the
OnNetworkingStatusChange() callback in case the GetWiFiInfo() fails.
Use GetWantedNetwork() return value as a fallback.

[nrf fromtree] [nrfconnect] Fix the case when the Wi-Fi info cannot be retrieved

---

config/zephyr/Kconfig

LIT functionality is provisional for Matter 1.3.
Set it as experimental for now.

[nrf noup] Mark `CHIP_ICD_LIT_SUPPORT` experimental

---

config/nrfconnect/chip-module/Kconfig.features
config/zephyr/chip-module/Kconfig.features

Aligned the MCUmgr Bluetooth transport Kconfig with the latest changes from Zephyr.
Ref: NCSDK-29061
> !!!!!!!!!! Please delete the instructions below and replace with PR description
>
> If you have an issue number, please use a syntax of
> `Fixes #12345` and a brief change description
>
> If you do not have an issue number, please have a good description of
> the problem and the fix. Help the reviewer understand what to expect.
>
> Make sure you delete these instructions (to prove you have read them).
>
> !!!!!!!!!! Instructions end

[nrf toup] config: align the MCUmgr Bluetooth transport Kconfig

---

src/lib/shell/commands/Device.cpp

It is better to call the ScheduleFactoryReset method from the Server because it also removes all fabrics and emits the Leave event whereas calling InitiateFactoryReset() removes only the persistent storage entries.
In this way, the Matter Shell command works in the same way as other factory reset sources.
We cannot upmerge it in an easy way because many vendors do not use chip server and there are multiple building issues.

[nrf noup] Shedule factory reset in Server using Matter Shell command

---

src/platform/nrfconnect/ConnectivityManagerImpl.cpp

This commit updates the IPv6 multicast subscription mechanism by explicitly using the MLDv2 join procedure. This change ensures proper registration for multicast addresses, improving reliability in multicast communication.

[nrf toup] [nrfconnect] Enable MLDv2 join procedure for IPv6 Multicasts

---

src/platform/Zephyr/ConfigurationManagerImpl.cpp

It can be squashed with the 0c49058 commit.

[nrf toup] Fix defines for ZMS

---

config/nrfconnect/chip-module/Kconfig
config/nrfconnect/chip-module/Kconfig.defaults
src/platform/nrfconnect/OTAImageProcessorImpl.cpp

Added support for multi-image dfu target while using SUIT.

[nrf toup] [nrfconnect] Add support for SUIT over Matter OTA

---

config/nrfconnect/chip-module/Kconfig
src/platform/nrfconnect/FactoryDataProvider.cpp

On nRF54L devices, we can use KMU to store the DAC private key, and allow using it directly by CRACEN.
By default, the DAC private key is encrypted so it needs 4 KMU slots.

[nrf toup] Migrate DAC to CRACEN KMU on nRF54L devices

---

config/nrfconnect/chip-module/Kconfig.defaults

Enabled DAC migration for all targets using Thread protocol, as Wi-Fi does not support PSA yet.

[nrf toup][nrfconnect] Enabled DAC migration by default for Thread

---

config/nrfconnect/chip-module/Kconfig
config/nrfconnect/chip-module/Kconfig.defaults
src/platform/nrfconnect/FactoryDataProvider.cpp

- Fixed wrong dependency in Kconfigs
- Fixed wrong bracket placement that causes overwriting DAC private key.

[nrf toup][nrfconnect] Fix DAC migration

---

config/nrfconnect/chip-module/Kconfig
config/nrfconnect/chip-module/Kconfig.defaults
src/platform/nrfconnect/FactoryDataProvider.cpp

- Fixed wrong dependency in Kconfigs
- Fixed wrong bracket placement that causes overwriting DAC private key.

[Backport v2.8-branch] [nrf toup][nrfconnect] Fix DAC migration

---

config/nrfconnect/chip-module/generate_factory_data.cmake
src/platform/nrfconnect/FactoryDataProvider.h

Until we do not have a proper solution for merging the factory data hex file with the firmware hex file, we need to flash the factory data manually. This commit allows doing that on nRF54H20 DK.

[nrf noup] Provide a workaround for Factory Data support on nRF54H

---

config/nrfconnect/chip-module/generate_factory_data.cmake
src/platform/nrfconnect/FactoryDataProvider.h

Until we do not have a proper solution for merging the factory data hex file with the firmware hex file, we need to flash the factory data manually. This commit allows doing that on nRF54H20 DK.

[Backport v2.8-branch][nrf noup] Provide a workaround for Factory Data support on nRF54H

---

config/nrfconnect/chip-module/Kconfig

`FPROTECT` should be disabled for nRF54L15 in app to allow correctly protecting whole region of mcuboot

[nrf toup] [nrfconnect] disable `FPROTECT` for nRF54L15

---

config/nrfconnect/chip-module/Kconfig

`FPROTECT` should be disabled for nRF54L15 in app to allow correctly protecting whole region of mcuboot
manual backport from https://github.com/nrfconnect/sdk-connectedhomeip/pull/508

[Backport v2.8-branch][nrf toup] [nrfconnect] disable `FPROTECT` for nRF54L15

---

src/crypto/CHIPCryptoPAL.cpp
src/crypto/PSASpake2p.cpp

When Spake2+ implementation for PSA crypto API is enabled:
- do not build the generic Spake2p nor its subclasses
- do not build Spake2pVerifier::Generate method that generates the verifier key out of the passcode, salt and iteration count.
Instead, provide the implementation Spake2pVerifier::Generate that uses PSA crypto API.
Note that using Spake2pVerifier::Generate requires setting CONFIG_PSA_WANT_ALG_PBKDF2_HMAC and
CONFIG_PSA_WANT_KEY_TYPE_SPAKE2P_KEY_PAIR_DERIVE Kconfig options.

[nrf noup] Implement Spake2pVerifier for PSA crypto

---

src/platform/nrfconnect/FactoryDataProvider.h

- factory data can be placed before or after settings partition
-added static_asserts, which checks whether factory data overlaps with settings partition
-added Kconfig which allow to choose the location of settings and factory data partition

[nrf toup] Factory data partition location change

---

config/nrfconnect/chip-module/CMakeLists.txt
config/zephyr/Kconfig

Introduced Kconfig option that allows to enable an ICD to send data report on entering the active mode.

[nrf toup][nrfconnect] Added config to enable report on active mode

---

config/nrfconnect/chip-module/Kconfig.defaults

The LIT devices seem to need bigger size of workqueue on 54L.

[nrf toup] Increased system workqueue size for LIT

---

src/platform/OpenThread/GenericNetworkCommissioningThreadDriver.h
src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.hpp

Dataset has to be cleared to allow commissioning to different network when CONFIG_CHIP_LAST_FABRIC_REMOVED_ERASE_ONLY is used.

[Backport v2.9-branch] Clear Thread Network after last fabric is removed

---

src/platform/OpenThread/GenericNetworkCommissioningThreadDriver.h
src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.hpp

Dataset has to be cleared to allow commissioning to different network when `CONFIG_CHIP_LAST_FABRIC_REMOVED_ERASE_ONLY` is used.

[nrf toup] Clear Thread Network after last fabric is removed

---

.github/workflows/release_tools.yaml

Bumped chip-build version that became obsolete and leads to bootstrap crash due to too old python version.

[nrf noup] Fix release tools workflow

---

src/platform/nrfconnect/FactoryDataProvider.cpp
src/platform/nrfconnect/FactoryDataProvider.h

A wrong device type was used for RRAM-based devices and inappropriate factory data addresses.

[nrf noup][nrfconnect] Fix DAC migration for MRAM-based devices.

---

config/nrfconnect/chip-module/Kconfig.defaults
src/platform/Zephyr/ConfigurationManagerImpl.cpp

We can speed up flash operations while performing a factory reset by disabling mpsl before that.
Thanks to that flash operations do not wait for mpsl synchronization and all write operations take less time.

[nrf toup] Disable mpsl before performing factory data

---

config/nrfconnect/chip-module/CMakeLists.txt
config/nrfconnect/chip-module/Kconfig

Removes support for child/parent images
> !!!!!!!!!! Please delete the instructions below and replace with PR description
>
> If you have an issue number, please use a syntax of
> `Fixes #12345` and a brief change description
>
> If you do not have an issue number, please have a good description of
> the problem and the fix. Help the reviewer understand what to expect.
>
> Make sure you delete these instructions (to prove you have read them).
>
> !!!!!!!!!! Instructions end

[nrf toup] config: nrfconnect: chip-module: Remove child/parent support

---

config/nrfconnect/chip-module/Kconfig.defaults

Increased the malloc heap size for 54L and moved MPSL stack size config to defaults, as it was set in all Matter samples.

[nrfconnect] Moved 54L specific configs to defaults

---

docs/guides/nrfconnect_factory_data_configuration.md

The argument description for the factory data generation script is incorrect. It should be `--user` instead of `--user-data`.

[nrf toup] Fix user data argument in factory data docs

---

docs/guides/nrfconnect_factory_data_configuration.md

Since the `nrfjprog` tool become deprecated all documents shall mention the `nrfutil device` tool.

[nrftoup] docs: guides: update nrfconnect factory data guide

---

config/nrfconnect/chip-module/Kconfig.defaults

The configuration of ACL RX count changed and new Kconfig is needed to bring back the previous configuration.

[nrf toup] Added rx count extra to fix an issue with acls count

---

src/platform/nrfconnect/wifi/WiFiManager.cpp

Replace static assert with runtime check due to wifi_scan_result.ssid size change.

[toup][nrfconnect] Fix compatibility with wifi driver

---

src/crypto/PSASessionKeystore.cpp

psa_key_attributes_t has to be initialized with PSA_KEY_ATTRIBUTES_INIT.

[crypto] Fix initialization of psa key attributes

---

src/platform/Zephyr/DiagnosticDataProviderImpl.cpp
src/platform/Zephyr/PlatformManagerImpl.cpp
src/platform/Zephyr/PlatformManagerImpl.h

Currently total operational hours are saved to NVM with `CONFIG_CHIP_OPERATIONAL_TIME_SAVE_INTERVAL`.
Certification tests require checking the value after 1 hour, restarting the DUT, and checking if the value has not changed, causing failures if given config is higher than 1.
This commit additionaly saves total operational hours to NVM everytime it is being read by `GetTotalOperationalHours` (writing only if currently stored value should be updated). This way value is stored with minimum frequency of 1 hour (if read request is sent frequently) and maximum frequency of `CONFIG_CHIP_OPERATIONAL_TIME_SAVE_INTERVAL`.
(cherry picked from commit 89e823e5d8065ce85a6e6b4c205e11db413c4535)

[nrf fromtree] [Zephyr] Save total operational hours on Read (#37259)

---

CODEOWNERS

Override codeowners to ncs-matter for whole sdk-connectedhomeip repository.

[nrf noup] CODEOWNERS: override codeowners to ncs-matter

---

scripts/west/west-commands.yml
scripts/west/zap_append.py
scripts/west/zap_common.py
scripts/west/zap_gui.py

Added zap_append command to the west.
use `west zap-append -h` to see all options.
Now you can add new clusters to the matter ZCL datamodel.
Use a `west zap-append` and provide the new cluster definitionsas XML files to add them to the zcl.json file.
You can generate the new zcl.json file by providing `-o, --output` argument, or overwrite the existing one.
The zcl_generate is integrated with `west zap-gui` commands.
If you want to use it call the `west zap-gui` command with the additional argument `--clusters`.
You can provide multiple clusters at once.
If you provide an additional `-j` / `--zcl-json` argument alongside the `--clusters` argument to the `west zap-gui` command, the new zcl.json will be created and contain the new clusters.
Tested on MacOS with Intel, and Ubuntu 24.04, and …

[nrf noup] Add zcl_generate to west command

---

.github/workflows/release_tools.yaml
scripts/build_python.sh

Updated release tools to build and capture all needed artifacts used for testing.

[nrf noup] workflow: release tools workflow

---

examples/chef/common/chef-dishwasher-mode-delegate-impl.cpp
examples/chef/common/chef-rvc-mode-delegate.cpp
examples/light-switch-app/cc13x4_26x4/src/AppTask.cpp
examples/light-switch-app/infineon/cyw30739/src/ZclCallbacks.cpp
examples/lighting-app/cc13x4_26x4/src/AppTask.cpp
examples/lighting-app/infineon/cyw30739/src/ZclCallbacks.cpp
examples/lock-app/cc13x4_26x4/src/AppTask.cpp
examples/lock-app/infineon/cyw30739/src/ZclCallbacks.cpp
examples/pump-app/cc13x4_26x4/main/AppTask.cpp
examples/pump-controller-app/cc13x4_26x4/main/AppTask.cpp
examples/thermostat/infineon/cyw30739/src/TemperatureManager.cpp
examples/thermostat/silabs/src/TemperatureManager.cpp
src/app/BUILD.gn
src/app/InteractionModelEngine.h
src/app/chip_data_model.cmake
src/app/chip_data_model.gni
src/app/clusters/icd-management-server/icd-management-server.cpp
src/app/clusters/icd-management-server/icd-management-server.h
src/app/reporting/ReportScheduler.h
src/app/server/BUILD.gn
src/app/util/AttributesChangedListener.h
src/app/util/BUILD.gn
src/app/util/MarkAttributeDirty.h
src/app/util/af-types.h
src/app/util/attribute-table.h
src/app/zap-templates/templates/app/attributes/Accessors-src.zapt
src/app/zap-templates/templates/app/attributes/Accessors.zapt
zzz_generated/app-common/app-common/zap-generated/attributes/Accessors.cpp
zzz_generated/app-common/app-common/zap-generated/attributes/Accessors.h

* Remove ICD server sources from chip_data_model.cmake
* Fix ICD dependencies
* Fix gn include warnings
* iOS TVCasting app: Add missing chip_project_config_include
* Fix ICD management server cluster dependecies
* Remove workaround for upstream issue 32628

Cherry pick build optimizations from upstream

---

config/nrfconnect/chip-module/CMakeLists.txt
config/nrfconnect/chip-module/Kconfig
config/nrfconnect/chip-module/Kconfig.features
src/app/server/Server.cpp
src/app/server/Server.h
src/crypto/BUILD.gn
src/crypto/CHIPCryptoPALPSA.h
src/crypto/PSAKeyAllocator.h
src/crypto/PSAOperationalKeystore.cpp
src/crypto/PSASessionKeystore.cpp
src/crypto/tests/TestPSAOpKeyStore.cpp
src/lib/core/CHIPConfig.h
src/platform/nrfconnect/BUILD.gn
src/platform/nrfconnect/KMUKeyAllocator.h
src/platform/nrfconnect/KMUSessionKeystore.h
src/platform/nrfconnect/args.gni

Let's review the code here first, before pushing it to the upstream repo.
See commit messages to see the changes.

[nrfconnect] Add platform crypto for KMU usage

---

.github/workflows/examples-nrfconnect.yaml

Use `env` instead of assigning PR body to variable, as `` ` `` is interpreted as shell command substitution.

[nrf noup] Fix parsing PR description

---

.vscode/launch.json
examples/platform/infineon/cyw30739/BUILD.gn
scripts/tools/check_includes_config.py
src/app/BUILD.gn
src/platform/BUILD.gn
src/test_driver/nrfconnect/CMakeLists.txt
src/test_driver/nrfconnect/main/runner.cpp

* Move GenericEventManagementTestEventTriggerHandler to separate source set.
* [nrfconnect] Allow running only specific test suites.

Cherry-pick changes from upstream

---

.github/workflows/examples-nrfconnect.yaml
scripts/build/builders/nrf.py

* Return error when ctest finds no tests.
* Always run Zephyr native tests.

Zephyr native tests improvements

---

config/common/cmake/chip_gn.cmake
config/nrfconnect/chip-module/CMakeLists.txt
scripts/west/zap_common.py
scripts/west/zap_generate.py
src/app/chip_data_model.cmake
src/app/common/BUILD.gn
src/app/common_flags.gni

Add a `--full` flag that generates full data model and puts it it `app-common/zap-generated` subdirectory.
Additionaly fix minor bug when equal paths have been shown as non- relative and zap file is not properly updated with zcl.json file
Also pull commit [nrf fromtree] Parametrize app-common zap-generated path from upstream

[nrf toup][nrfconnect] Add `--full` flag to zap-generate and parametrize app-common zap-generated path

---

src/platform/Zephyr/DiagnosticDataProviderImpl.cpp
src/platform/Zephyr/PlatformManagerImpl.cpp
src/platform/Zephyr/PlatformManagerImpl.h

Currently total operational hours are saved to NVM with `CONFIG_CHIP_OPERATIONAL_TIME_SAVE_INTERVAL`.
Certification tests require checking the value after 1 hour, restarting the DUT, and checking if the value has not changed, causing failures if given config is higher than 1.
This commit additionaly saves total operational hours to NVM everytime it is being read by `GetTotalOperationalHours` (writing only if currently stored value should be updated). This way value is stored with minimum frequency of 1 hour (if read request is sent frequently) and maximum frequency of `CONFIG_CHIP_OPERATIONAL_TIME_SAVE_INTERVAL`.
(cherry picked from commit 89e823e5d8065ce85a6e6b4c205e11db413c4535)

[Backport v2.9-branch][nrf fromtree] [Zephyr] Save total operational hours on Read

---

src/app/server/Server.cpp
src/app/server/Server.h
src/app/tests/BUILD.gn
src/app/tests/TestServer.cpp
src/include/platform/CHIPDeviceEvent.h
src/platform/fake/PlatformManagerImpl.h
src/test_driver/nrfconnect/prj.conf

Add kFactoryReset event and post it at the beginning of ScheduleFactoryReset.
Fixes [KRKNWK-20041](https://nordicsemi.atlassian.net/browse/KRKNWK-20041)

[Backport v2.9-branch] [nrf fromtree] Add factory reset event

---

src/platform/OpenThread/GenericNetworkCommissioningThreadDriver.cpp
src/platform/OpenThread/GenericNetworkCommissioningThreadDriver.h

* Postpone `RevertConfiguration` until OpenThread is initialized.
* Clear SRP host and services before reverting dataset.
* Abort revert if creating new backup.

[nrf fromtree] OpenThread: Clear SRP host and services during RevertConfiguration

---

examples/platform/nrfconnect/util/include/FabricTableDelegate.h

* Close commissioning window on last fabric removal. It will be reopened depending on `CHIP_LAST_FABRIC_REMOVED_ACTION`.
* Update handler to match implementation in NCS.

[nrf toup] Don't advertise when waiting for last fabric removed action

---

config/zephyr/Kconfig

The LIT configuration in Matter samples can be slightly changed to achieve lower power consumption.

[nrf noup] Optimized configuration for LITs

---

.github/workflows/release_tools.yaml

Update the release tools workflow to include archiving the matter_testing wheel package

[noup] github: workflow: Archive matter_testing wheel

---

config/nrfconnect/chip-module/Kconfig

Set packet buffer pool size to 15.

[nrf toup] Revert size of Packet Buffer Pool to previous value

---

config/nrfconnect/chip-module/Kconfig.defaults

With introduction of dedicated memory pools for nRF70 Wi-Fi driver, redistribute current heap size among the
driver heap and kernel heap.
> Add following line to test this PR against different NCS revision:
> NCS PR: nrfconnect/sdk-nrf/pull/<PR ID>

[nrfconnect] Reconfigure memory pool sizes

---

src/platform/nrfconnect/wifi/WiFiManager.cpp

Added disconnection result code to the debug log. Also moved the debug log to other place to print the result WIFI_RESON code that contains more information than WLAN_RESON code.

[nrf toup] Added disconnection code to the debug log

---

src/platform/Zephyr/ConfigurationManagerImpl.cpp
src/platform/Zephyr/KeyValueStoreManagerImpl.cpp

use settings_load_one function to load one key/value settings entry instead of settings_load_subtree_direct.
This will avoid loading all the keys for some storage backends. Simplify as well the Delete function by skipping loading the value before deleting it.
NCS PR: nrfconnect/sdk-nrf/pull/20691

[nrf toup] simplify Key/Value Get function

---

src/messaging/tests/BUILD.gn
src/test_driver/nrfconnect/prj.conf

* Revert disabling tests
* Use default ICD poll intervals in tests

Fix and re-enable failing tests

---

src/platform/Zephyr/ConfigurationManagerImpl.cpp
src/platform/Zephyr/KeyValueStoreManagerImpl.cpp

Simplify the Key/Value _Get function
Adds the support for legacy ZMS backend for Settings
NCS PR: https://github.com/nrfconnect/sdk-nrf/pull/20691

[Backport v3.0-branch] new ZMS backend changes

---

.github/workflows/release_tools.yaml

Ubuntu 20.04 is deprecated and cannot be used to run build of the release tools. The deprecation took place on 15.04.2025.
Switched to the next stable version: 22.04.

[nrf noup] Bump the Ubuntu version for release tools.

---

src/app/zap-templates/zcl/data-model/chip/bridged-device-basic-information.xml

Set correct access permissions for `NodeLabel` in `BridgedDeviceBasicInformation` cluster.

[nrf noup] Fix TC-ACE-2.2

---

src/app/zap-templates/zcl/data-model/chip/bridged-device-basic-information.xml

Set correct access permissions for `NodeLabel` in `BridgedDeviceBasicInformation` cluster.

[Backport v2.9-branch] [nrf noup] Fix TC-ACE-2.2

---

scripts/west/zap_common.py

When using `west zap-gui` on Windows, if the ZAP file and any of the required files (ZCL or app templates) are located on different drives, the command fails with: `ValueError: 'c:\\ncs\\v3.0.0-rc1\\modules\\lib\\matter\\src\\app\\zap-templates\\zcl\\zcl.json' and 'D:\\Code\\project\\src\\default_zap' have different anchors` 
This occurs because `pathlib.Path.relative_to()` method cannot compute relative paths between different drives in Windows. The issue happens in both scenarios:
1. With default ZCL path from SDK (C: drive) and project on another drive (D: drive)
2. Even when specifying a custom ZCL file with `-j` option, if app-templates.json remains on a different drive
In `update_zcl_in_zap()` function, the code attempts to calculate relative paths using `relative_to()` but doesn't …

fix: handle paths on different drives in Windows for zap-gui

---

scripts/west/zap_common.py

Both `zap --version` and `zap-cli --version` do the same thing more or less, but `zap` is heavier to run since it starts Electron just to do `--version`. Since the user may only care about `zap-cli` commands (e.g. `west zap-generate`), requiring that all `west zap-*` commands call `zap` just to get a version check increases the amount of resources and dependencies required.
Instead, just use `zap-cli` to get the version.

[nrf noup] Use ZAP CLI for version check

---

scripts/west/zap_common.py

Currently x86 ZAP is always downloaded on Linux & Windows. This change looks at the architecture of the system to download either x86_64 or arm64 binaries as provided by ZAP releases
This is the Linux / Windows equivalent to #574 which similarly downloads ARM64 binaries for Darwin systems on Apple Silicon.

[nrf noup] Use proper ZAP package for Linux/Windows with ARM CPUs

---

src/inet/tests/TestInetEndPoint.cpp

Description:
- TestInetEndPoint was not hermetic, it required at least one network interface connected to a link and up.
- There was a comment before to skip tests if the link was not up, but it was not actually skipping the test. This made it fail for me when working offline and trying to run unit tests.
Testing done:
- Test passes with and without link up.
(cherry picked from commit b2a86bddd3c2b34e33e0defbef61b37f76267e1d)

[nrf fromtree] Fix TestInetEndPoint to pass even when computer is offline

---

src/app/zap-templates/zcl/data-model/chip/bridged-device-basic-information.xml

Set correct access permissions for `NodeLabel` in `BridgedDeviceBasicInformation` cluster.

[Backport v3.0-branch] [nrf noup] Fix TC-ACE-2.2

---

.github/workflows/release_tools.yaml

Add `enable_im_pretty_print=true` to enable detailed debug logs.

[nrf noup] Build chip-tool with logs

---

config/zephyr/Kconfig
src/platform/Zephyr/ConfigurationManagerImpl.cpp
src/platform/Zephyr/ConfigurationManagerImpl.h

Added functionality that can be enabled using Kconfig option and allows to measure the time between factory reset schedule and factory reset end to know this process duration.
Tested using automated tests

[nrf noup] Added measuring factory reset time

---

scripts/tools/zap/generate.py
scripts/west/zap_generate.py

Now, the zap_generate Python script uses common targets to
generate Matter Data Model ZAP and Code from zap_regen_all.py,
located in the Matter SDK. This approach allows reusing of a
common script to generate the whole Data Model and append a
newly created cluster.
Tested in nrf

Align full zap generation to changes in Matter Upstream

---

src/lib/dnssd/platform/Dnssd.h
src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.hpp

The DNS browse for vendor id subtype does not work, as full name does not fit in the provided buffer.
By the way of investigating this issue couple of other issues were found:
* Started to use full service name including subtypes for dns browse results handling in Thread implementation
* Fixed max commissionable and commissioner service name sizes that didn't include . character
* Fixed kDnssdFullTypeAndProtocolMaxSize that did not include _sub phrase
Tested manually using `dns browse` command from the dns shell for the _V and _L subtypes.

[nrf fromlist][dnssd] Fixed buffer sizes for dns names

---

scripts/west/zap_generate.py

Allows processing multiple Zap files at once by providing a YAML file with Zap file list.
Tested locally

[nrf noup] Extend zap-generate to process multiple files at once

---

src/platform/nrfconnect/wifi/WiFiManager.cpp
src/platform/nrfconnect/wifi/WiFiManager.h

The net_mgmt event representation changed from 32-bit to 64-bit value, therefore align with this change.
Tested in NCS CI
NCS PR: nrfconnect/sdk-nrf/pull/22993

[nrf toup][nrfconnect] Align with Zephyr net_mgmt API changes

---

src/crypto/PSAOperationalKeystore.cpp

The pending keypair was handled in a wrong way in the PSA PAL.
This keypair should be saved to ITS as volatile persistence, then all operations should be done using this instance, and it must be saved to persistent storage in the CommitOpKeypairForFabric function.
Previously, the same KeyId was used both to active and pending keypairs, and when a failsafe occurs, then this key has been removed and there is no key for the fabric anymore.
Main changes:
- PersistentP256Keypair::Generate generates a pending keypair as volatile with additional usage flag PSA_KEY_USAGE_COPY.
- In the CommitOpKeypairForFabric function, the pending keypair is copied to a persistent location, and the key ID for fabric is replaced.
In progress

[nrf toup] [Crypto] Fix the wrong handling PSA pending keypair.
