nrfconnect/sdk-connectedhomeip

src/platform/OpenThread/OpenThreadUtils.cpp
=> [nrf fromlist] Prepare the code for OpenThread update

docs/guides/nrfconnect_android_commissioning.md, docs/guides/nrfconnect_examples_software_update.md, scripts/requirements.esp32.txt, scripts/requirements.mbed.txt, src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/CHIPToolActivity.kt, src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/ChipClient.kt, src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/bluetooth/BluetoothManager.kt, src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/OnOffClientFragment.kt, src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/SensorClientFragment.kt, src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/echoclient/EchoClientFragment.kt, src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/provisioning/DeviceProvisioningFragment.kt, src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/provisioning/EnterNetworkFragment.kt, src/android/CHIPTool/app/src/main/res/values/strings.xml, src/controller/java/CHIPDeviceController-JNI.cpp, src/controller/java/src/chip/devicecontroller/ChipDeviceController.java
* Bring in fix for Android CHIPTool build, and enhancement to exit to the main screen after commissioning
* Bring in documentation changes
* Try to fix failing CI jobs due to conflicting Python requirements
=> Bring in various fixes from the upstream and fix CI

src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/SensorClientFragment.kt, src/android/CHIPTool/app/src/main/res/layout/sensor_client_fragment.xml, src/android/CHIPTool/app/src/main/res/values/strings.xml
Automatically resolve the device address using DNS-SD upon entering the "Sensor Clusters" screen.
Also, bring in minor fixes for the sensor time series graph.
=> [nrf noup] Update device address on sensors screen start

.github/.wordlist.txt, docs/guides/chip_tool_guide.md, examples/chip-tool/README.md, src/app/server/Server.cpp
This commit is needed to update the documentation with a guide for the chip-tool controller.
=> Cherry-pick PRs from Matter upstream: #16637 and #16703

zephyr/module.yml
Replace old LicenseRef with the new one currently in use.
Ref: NCSIDB-717
Signed-off-by: Lukasz Duda <lukasz.duda@nordicsemi.no>
=> license: Replace old license reference

config/nrfconnect/chip-module/CMakeLists.txt
What is being fixed?  Examples:
* Upmerge
Upmerge fixes
=> [nrf noup] update the Zephyr include path.

config/nrfconnect/chip-module/Kconfig.mcuboot.defaults, examples/light-switch-app/nrfconnect/main/AppTask.cpp, examples/lighting-app/nrfconnect/main/AppTask.cpp, examples/lock-app/nrfconnect/main/AppTask.cpp, examples/platform/nrfconnect/util/OTAUtil.cpp, examples/pump-app/nrfconnect/main/AppTask.cpp, examples/pump-controller-app/nrfconnect/main/AppTask.cpp, src/app/clusters/operational-credentials-server/operational-credentials-server.cpp, src/app/server/Server.h, src/platform/nrfconnect/CHIPDevicePlatformConfig.h, src/platform/nrfconnect/OTAImageProcessorImpl.cpp, src/platform/nrfconnect/OTAImageProcessorImpl.h, src/setup_payload/QRCodeSetupPayloadGenerator.cpp
Added bug fixes to the Matter core:
* QSPI sleep fix
* QR code generation fix
=> Added bug fixes to the Matter core

.github/workflows/examples-nrfconnect.yaml, integrations/docker/ci-only-images/chip-cirque-device-base/Dockerfile, scripts/constraints.txt, scripts/requirements.txt
Fetch cbor2 in bootstrap.sh
Cherry-pick a change to fix cirque CI
Update Python modules on nRF Connect update to harden things in the future.
Make build of nRF Connect examples optional (continue-on-error).
=> [nrf noup] Make sdk-connectedhomeip green again

src/platform/Zephyr/BUILD.gn, src/platform/Zephyr/DiagnosticDataProviderImpl.cpp, src/platform/Zephyr/InetUtils.h, src/platform/nrfconnect/BUILD.gn, src/platform/nrfconnect/OTAImageProcessorImpl.cpp, src/platform/nrfconnect/Reboot.cpp, src/platform/nrfconnect/Reboot.h
Cherry-pick fix for SoftwareUpdateCompleted boot reason detection.
Fix build of native_posix unit tests.
=> [nrf fromtree] [nrfconnect] Improve SoftwareUpdateCompleted boot reason detection

src/platform/nrfconnect/wifi/WiFiManager.cpp
Fix the build breakage with latest Wi-Fi driver PR: https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-8495/7/testReport/
=> Fix build latest wifi

src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp
Do not disconnect/reconnect to the already attached network.
=> [nrf noup] wifi: RevertConfiguration optimization

config/nrfconnect/chip-module/Kconfig.features
Updates required MCUmgr configuration for zephyr upmerge changes.
=> [nrf noup] Update required MCUmgr config

src/platform/Zephyr/DiagnosticDataProviderImpl.cpp
15.4 drivers in Zephyr set EUI-64 as the link-layer address of the corresponding interface. However, Hardware Address field in the General Diagnostics cluster is supposed to return Extended Address for Thread interfaces according to the specification.
Make sure the diagnostic data provider returns the extended address for the concerned field.
=> [nrf fromlist] [Zephyr] Fix General Diagnostics Hardware Address

scripts/requirements.nrfconnect.txt, scripts/setup/nrfconnect/get_zap.py, scripts/tools/zap/generate.py
The helper script is going to find recommended ZAP version in the Matter repository, and download and extract the package from the ZAP releases.
=> [nrf noup] Added script for downloading recommended zap package

src/lib/address_resolve/AddressResolve_DefaultImpl.cpp
If we cross out min lookup time boundary between when we get a result and when the next ReArmTimer call happens, we want to make sure we don't end up waiting until our max lookup boundary.
Fixes https://github.com/project-chip/connectedhomeip/issues/25049
=> [nrf fromlist] Make sure that we don't miss lookup result notifications.

scripts/tools/zap/tests/available_tests.yaml, src/app/zap-templates/app-templates-testing.json, src/controller/CHIPDeviceControllerFactory.cpp, src/controller/CHIPDeviceControllerFactory.h, src/protocols/BUILD.gn
Provided all needed changes before NCS 2.4.0 RC1 TAG:
=> Tag 1.1.0.1 followup

config/nrfconnect/chip-module/Kconfig.features, src/platform/nrfconnect/wifi/WiFiManager.cpp, src/platform/nrfconnect/wifi/WiFiManager.h
Bug fixes for Wi-Fi platform:
- Integrated new DISCONNECT_COMPLETED event to fix reconnection handling
- Replaced old Kconfig name for nRF7002 EK with the new one to fix compilation issues
=> Wi-Fi fixes

scripts/setup/constraints.txt, scripts/setup/requirements.esp32.txt, src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp
Change:
- `otLinkCslGetPeriod` to `otLinkGetCslPeriod`
- `otLinkCslSetPeriod` to `otLinkSetCslPeriod`
=> [nrf noup] Change to new csl interface.

src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp, src/platform/nrfconnect/wifi/WiFiManager.cpp, src/platform/nrfconnect/wifi/WiFiManager.h
Currently, the Wi-Fi driver supports the recovery mechanism and it seems that it works properly so we can remove our recovery mechanism.
=> [nrf noup] Remove recovery mechanism for Wi-Fi connection

src/platform/nrfconnect/wifi/WiFiManager.cpp
It's pointless to issue a connect request in case
no valid SSID has been found.
=> [nrf noup] wifi: avoid unwanted connect request

.github/workflows/release_tools.yaml
Added all changes to release tools github workflow needed to work with Matter 1.2.
=> [nrf noup] Aligned release tools to Matter 1.2

src/app/clusters/color-control-server/color-control-server.cpp
…the thread network can be spammed (#31778)
* Adding diff
* Restyled by clang-format
---------
Cherry-picked commit: 935aa450
=> [nrf fromtree] When dimming a light/bulb over time or changing color, the thread network can be spammed fix

config/nrfconnect/chip-module/Kconfig.defaults, src/crypto/CHIPCryptoPALPSA.cpp, src/crypto/CHIPCryptoPALPSA.h, src/crypto/PSASessionKeystore.cpp, src/crypto/PSASpake2p.cpp, src/platform/nrfconnect/CHIPPlatformConfig.h
Aligned Spake2+ algorithm to the Oberon PSA core v1.2.1.1
=> [nrf noup] Spake2+ alignments regarding the newest Oberon version

scripts/setup/constraints.txt
Bump prompt-toolkit requirement to fix ptpython version update (#30987)
(cherry picked from commit 1536ca20c5917578ca40ce509400e97b52751788)
=> [nrf fromtree] Bootsrtap.sh fix

src/platform/nrfconnect/wifi/NrfWiFiDriver.cpp, src/platform/nrfconnect/wifi/NrfWiFiDriver.h, src/platform/nrfconnect/wifi/WiFiManager.cpp, src/platform/nrfconnect/wifi/WiFiManager.h
This commit implement minors from previous wifi fix signed PR number 404.
=> [nrf noup] followup to wifi issues fix

src/platform/nrfconnect/wifi/WiFiManager.cpp, src/platform/nrfconnect/wifi/WiFiManager.h
This commit implements directed scanning and single ssid scanning while commissioning.
=> [nrf noup] Wifi directed scan with single scan

.github/workflows/create-manifest-pr.yaml
GitHub action to automatically create Pull Requests in the manifest repo when updating revisions
https://nordicsemi.atlassian.net/browse/NCSDK-27194
=> CI:make PR to manifest

src/platform/nrfconnect/wifi/WiFiManager.cpp, src/platform/nrfconnect/wifi/WiFiManager.h
* Handle supplicant ready/not ready events.
* Reconnect to previously connected network.
* Restore low power mode.
=> [nrf toup][nrfconnect] Reconnect to network after RPU recovery

.github/workflows/examples-nrfconnect.yaml
* Skip job if not a PR.
* Ignore grep errors.
* Check if PR description is not empty.
* Allow running Zephyr native test with workflow dispatch.
=> Fix workflow

.github/workflows/examples-nrfconnect.yaml
Not needed after recent upmerge.
=> Remove linking workaround

src/platform/nrfconnect/wifi/WiFiManager.cpp, src/platform/nrfconnect/wifi/WiFiManager.h
=> [Backport v2.9-branch][nrf toup][nrfconnect] Reconnect to network after RPU recovery

src/app/server/Server.cpp, src/app/server/Server.h, src/app/tests/BUILD.gn, src/app/tests/TestServer.cpp, src/include/platform/CHIPDeviceEvent.h, src/platform/fake/PlatformManagerImpl.h, src/test_driver/nrfconnect/prj.conf
Add `kFactoryReset` event and post it at the beginning of `ScheduleFactoryReset`.
=> [nrf fromtree] Add factory reset event

src/messaging/tests/BUILD.gn
Disable until these tests are fixed in KRKNWK-20114.
=> [nrf noup] Disable some failing tests

.github/workflows/examples-nrfconnect.yaml
Added entry in workflows that runs unit tests on native posix with ZMS enabled.
=> [nrf noup] Added running unit tests on native posix with ZMS

src/app/clusters/user-label-server/user-label-server.cpp, src/app/tests/suites/TestUserLabelClusterConstraints.yaml, src/platform/DeviceInfoProvider.cpp, src/transport/raw/TCP.cpp, src/transport/raw/tests/TestTCP.cpp
Cherry-pick fixes for:
* CVE-2024-56318
* CVE-2024-56319
=> Cherry-pick CVEs fixes from upstream

src/app/clusters/user-label-server/user-label-server.cpp, src/app/tests/suites/TestUserLabelClusterConstraints.yaml, src/platform/DeviceInfoProvider.cpp, src/transport/raw/TCP.cpp, src/transport/raw/tests/TestTCP.cpp
Cherry-pick fixes for:
* CVE-2024-56318
* CVE-2024-56319
=> [Backport v2.9-branch] Cherry-pick CVEs fixes from upstream

config/nrfconnect/chip-module/Kconfig.defaults, src/platform/Zephyr/BLEManagerImpl.cpp
* Replace POSIX_MAX_FDS with ZVFS_OPEN_MAX
=> Changes for upmerge 2025.04.23

config/nrfconnect/chip-module/Kconfig, config/nrfconnect/chip-module/Kconfig.defaults
Changed values of a few ICD configs to optimize the devices behavior.
Automated tests in CI
=> [nrf toup][nrfconnect] Changed the default ICD config values

src/crypto/PSAOperationalKeystore.cpp
=> [backport 3.1] [nrf toup] [Crypto] Fix the wrong handling PSA pending keypair.
